- source/smart-contracts/guides/local-simulate.rst
- source/smart-contracts/references/host-fns.rst
- source/smart-contracts/references/simulate-context.rst
They are removed from the next version of the smart contract libraries/API.
> Remove slotNumber, blockHeight, finalizedHeight from the contexts.

- source/testnet/references/transactions.rst
Removes the references to `baker set-*-key` and delegation from the transactions page.
> transactions: remove obsolete transactions and references to delegation.

- source/testnet/guides/accounts-transactions.rst
- source/testnet/guides/become-baker.rst
- source/testnet/references/id-accounts.rst
- source/testnet/references/query-node.rst
- source/testnet/references/transactions.rst
- source/testnet/see-also/glossary.rst
Reworded how we specify the different time constraints to try to give a consistent view of the timeline. Also removed the definition of baker ID as we don't really need it.
> baker: reword some blurry concepts and time contraints

- source/testnet/references/concordium-client.rst
Also removes the old caveat about running from a specific directory, that is no
longer needed.
> Add a little bit of documentation for grpc-ip and grpc-port commands.

- source/testnet/see-also/glossary.rst
From memory, this should be `1-(1-f)^a`, not `1-(1-f)a`.
Could someone verify?
> fixed typo in winning probability in glossary

- source/testnet/references/concordium-client.rst
update documentation to reflect refactor of config account add to config account name, as well as the name parameter not being optional.
> Reflect refactor of add -> name

- source/smart-contracts/references/host-fns.rst
Update host function docs to match what is actually on the chain.
Details:
- Remove `get_slot_number`, `get_block_height`, `get_finalized_height`.
- Add `get_policy_section`.
- Correct parameter names and return values.
- Clarify and correct descriptions.
Closes CB-1045.
> Update host fns and minor improvements

- source/testnet/guides/accounts-transactions.rst
The purpose of this pull request, is just to change a small phrasing error in the guide on how to move funds to the shielded balance.
Resolves #93 
Lets' was changed to Let's, and **Shielded Balance** was changed to **Balance**
> Changed incorrect phrasing

- Makefile
- README.md
- make.bat
Enable caching of builds.
Explain how to get warnings from TODOs.
- Removing the `-E` flag from the make files.
- Update the README
> Enable caching

- source/conf.py
- source/testnet/concepts/id-accounts.rst
- source/testnet/guides/accounts-transactions.rst
- source/testnet/guides/become-baker.rst
- source/testnet/guides/run-node.rst
- source/testnet/index.rst
- source/testnet/installation/get-the-app.rst
- source/testnet/mobile-wallet/explore-more.rst
- source/testnet/mobile-wallet/get-started.rst
- source/testnet/references/concordium-client.rst
- source/testnet/references/manage-accounts.rst
- source/testnet/references/query-node.rst
- source/testnet/references/transactions.rst
To ensure consistency, the support and feedback footer should be defined once and reused across the pages.
- Added the footer using the sphinx setting [`rst_epilog`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_epilog)
- Removed the support and feedback section from every rst file
> Add support and feedback section to be appended in every rst file

- source/testnet/guides/become-baker.rst
We used `amountToStake` one place and `amount-to-stake` in another. Changed all of them to the latter version.
`amountToStake` -> `amount-to-stake`
> Fix placeholder name

- source/testnet/guides/become-baker.rst
Warn that users should not encrypt baker credentials since it is hard to start a node with them with the currently available distributions.
> Add a warning to not encrypt baker credentials.

- source/_templates/index.html
The outdated testnet4 documentation should have a link to the current mainnet documentation.
Should be merged and deployed at mainnet launch.
- Add link to testnet4 page for mainnet documentation
> Add link to testnet4 page for mainnet documentation

- .github/workflows/lint.yml
- scripts/build.sh
Currently, the build check fails, because it is not using the build script
- Make the build check, use the build script
> CI checks build using scripts/build.sh

- source/shared/smart-contracts/guides/local-simulate.rst
Make the json valid by removing the trailing comma.
> Remove trailing comma to make json valid

- source/mainnet/net/installation/downloads.rst
- source/testnet/net/installation/downloads.rst
We had few support issues regarding running our command-line tools on mac.
This should help amend this issue.
We might also need to address the issue that people without knowledge of terminal usage is downloading our terminal tools.
- Describe how to make the tool executable with `chmod` and how to grant it permission to run.
> Explain how to run C. client and cargo-concordium on mac

- source/testnet/net/installation/downloads.rst
The testnet version of the DW for MacOS is not signed, so a description of how to allow it to run was added to the downloads page. 
The description on how to allow the DW to run on MacOS was added.
> Added description for non-signed Mac software

- source/shared/net/guides/become-baker.rst
- source/shared/net/mobile-wallet/explore-more.rst
Changed wording about accounts to explain that Desktop Wallet accounts can't be imported into the client.
Changed paragraph about account import.
> changed account import info to become baker

- source/mainnet/net/installation/downloads.rst
SHA256 checksums were requested for verification of DW and client downloads, so these had to be added to the downloads page.
SHA256 checksums were added to all DW and concordium-client downloads.
> Added SHA256 checksums to DW and client downloads

- source/mainnet/_templates/index.html
After fixing the testnet landing page links, the linux guide link turned out to still be broken because of a typo.
Typo in Linux link is now fixed.
> Fixed typo in linux node link

- source/testnet/net/guides/run-node-macos.rst
Add a step explaining how to move the `baker-credentials.json` file to a location accessible by the mac node service (the config folder).
The mac node runs as a system service, so if you keep your `baker-credentials.json` file in e.g. a user's Downloads folder, then the service won't be able to read it and thus not able to run.
Add an additional step in the baker section and minor changes to paths and phrasing.
> Explain moving baker-credentials to accessible location

- source/testnet/net/guides/run-node-ubuntu.rst
There was a dead link on the Run a Node on Ubuntu page.
Link was fixed.
> Fixed a dashboard link in Run a node Ubuntu

- source/mainnet/net/desktop-wallet/update-application.rst
- source/mainnet/net/index.rst
- source/mainnet/net/installation/downloads.rst
From DTW version 1.2 and onwards, the application features automatic updates. This PR ensures our documentation describes how this works, and what to do (manually updating) if this is not supported. 
- Added page describing both automatic and manual update process
Closes #232
> added documentation for automatic updates (mainnet only)

- source/mainnet/net/installation/downloads.rst
Fix link to mainnet debian distribution 1.1.3 
- Update mainnet debian distribution link
- Update checksum
> Fix link to mainnet debian distribution 1.1.3

- source/testnet/net/resources/release-notes.rst
Add testnet release note section for release of concordium-node 1.1.3
> Update testnet release notes with concordium node 1.1.3

- source/mainnet/_templates/index.html
The "run a node links" on the landing page for Mainnet had a / too much, causing the links to not work.
Removed the /'s.
> Fixed links on landing page

- source/mainnet/_templates/index.html
- source/shared/net/concepts/id-accounts.rst
- source/shared/net/guides/become-baker.rst
- source/shared/net/guides/deciding-wallet.rst
- source/testnet/net/resources/release-notes.rst
Some of the links on the landing page died after updating the mobile wallet docs, and some old labels also had to be updated.
Updated links and labels.
> Updated dead links after MW doc update

- source/shared/net/references/transactions.rst
_Rename transaction commands after name change from GTU to CCD
Changed commands in transactions.rst
> Rename concordium-client transaction commands

- source/shared/net/references/transactions.rst
- source/testnet/net/references/transactions.rst
_Changes to concordium-client were included in both testnet and mainnet docs, but are currently only relevant for testnet.
_Changed the topic Concordium Client transactions in testnet to include changes. Same topic for mainnet doesn't include changes.
> client transactions only changed for testnet not mainnet

- source/mainnet/net/resources/release-notes-mainnet.rst
Copy&paste of testnet release of concordium-client v3.0.4 to mainnet release notes.
Added conccordium-client v3.0.4.
> Added concordium-client v3-0-4 to release notes - don't merge before enterprise identities release

- source/mainnet/net/guides/enterprise-identities.rst
Exchanges are asking for hashes on the downloads for enterprise identities
- Added sha256 checksums for the linked files on enterprise identities page.
> checksums on enterprise downloads

- source/mainnet/net/installation/downloads.rst
- source/mainnet/net/resources/release-notes-mainnet.rst
- source/mainnet/variables.rst
- source/testnet/net/installation/downloads.rst
- source/testnet/net/resources/release-notes.rst
To prepare for release on 17 December, updated release notes are needed.
Updated mainnet release notes with node 3.0.0 information and android app version info. Updated testnet release notes with android app version info.
- [X ] I accept the above linked CLA.
> Updated release notes for mainnet and testnet

- source/mainnet/net/installation/downloads.rst
The AppImage link was placed slightly in the wrong place
Added a bit a new line to place it correctly.
> Fixed formatting of Appimage link

- source/mainnet/net/guides/company-identities.rst
- source/mainnet/net/index.rst
As per higher authority, change all instances of "enterprise" to "company" in the Enterprise identities guide.
Replaced word as needed.
> Change enterprise to company in all instances.

- source/mainnet/conf.py
- source/testnet/conf.py
To enable conditional text in Sphinx and allow for more single sourcing of content.
Added section at end of each conf.py file to enable tags so that the built in only function works.
> Updated conf.py for mainnet and testnet to enable conditional text

- source/mainnet/_templates/index.html
- source/shared/net/concepts/id-accounts.rst
- source/shared/net/resources/glossary.rst
Remove all traces of GTU from documentation text.
Updated Glossary file as this was the last remaining instance of GTU. Added CCD.
> Updated glossary to remove GTU, add CCD.

- source/shared/smart-contracts/general/contract-module.rst
To fix a typo that made a note appear incorrectly.
Added a missing space between .. and note::
- [ X] My code follows the style of this project.
- [ X] The code compiles without warnings.
- [ X] I have performed a self-review of the changes.
- [X ] I accept the above linked CLA.
> Added missing space for note

- source/shared/net/guides/run-node-macos.rst
Make it clear that you must insert the baker credential key-pair *underneath* the `<dict>` tag. 
This caused an issue for at least a single user, who contacted our support.
Here is a snippet of the service file to clarify the intent of this PR.
```
...
<key>EnvironmentVariables</key>
<dict>
<key>CONCORDIUM_NODE_LISTEN_PORT</key>
<string>8888</string>
...
```
We could also consider having the baker credentials key-pair already present in the service file but commented out.
Then we would need to explain to the users that they should remove the comment markers (``) when they want to become bakers. But I fear that this might cause even more trouble for the users.
Explain that it should be inserted underneath the dict tag.
> Clarify configure baker docs

- source/mainnet/net/guides/run-node-ubuntu.rst
- source/testnet/net/guides/run-node-ubuntu.rst
People may wonder whether they need to adjust the given path to something related to their setup. This is not the case. This update clarifies that the string is the genesis hash.
Furthermore, the testnet documentation used the same hash as the mainnet documentation. This was a mistake since testnet has a different genesis hash.
This pull request clarifies the documentation and fixes a bug in the testnet documentation.
Added a note explaining the meaning of the provided path and fixed hash in testnet documentation.
> Added note about default path in run-node-ubuntu

- source/shared/smart-contracts/tutorials/piggy-bank/testing.rst
There was a reference in code that was not caught when references to GTU were replaced with CCD.
Updated the code to reference CCD.
Closes #401
> Fix one reference to gtu in Smart Contract code example

- source/mainnet/net/guides/run-node-ubuntu.rst
- source/shared/net/desktop-wallet/install-ledger-app.rst
- source/shared/net/guides/baker-windows.rst
- source/shared/net/nodes/troubleshoot-macos.rst
- source/shared/net/references/concordium-client.rst
- source/shared/net/references/transactions.rst
- source/testnet/net/guides/run-node-ubuntu.rst
In support of #417 
This will make the copy button behave correctly in all examples, including multi-line ones.
> Add `$` to command examples where they were missing.

- source/shared/net/nodes/troubleshoot-macos.rst
The commands were broken due to the space in `Concordium Node`. The space should either be escaped with `\`, i.e. `...Concordium\ Node...`, or the whole argument should be quoted.
Quoted the commands
> Fix commands in mac troubleshooting

- README.md
Correct the links in the readme. It is http://127.0.0.1/net/ for both mainnet and testnet when developing.
Update links in readme
> Fix development links in readme

- source/mainnet/net/index.rst
- source/mainnet/net/installation/downloads-testnet.rst
- source/mainnet/net/installation/downloads.rst
Due to a problem with functionality of tabs, it wasn't possible to link directly to a tab with bookmarks/anchors/permalinks. This was problematic when notifying users about updated download files.
Added downloads page for testnet and removed tabs on both downloads pages.
> Add downloads page for testnet

- source/shared/smart-contracts/general/develop-contracts.rst
- source/shared/smart-contracts/tutorials/piggy-bank/testing.rst
- source/shared/smart-contracts/tutorials/piggy-bank/writing.rst
Fix docs.rs links in the documentation found after running the link checker.
- Fix the links
> Fix broken links to docs.rs

- source/mainnet/net/desktop-wallet/reset-data.rst
- source/mainnet/net/index.rst
- source/mainnet/net/resources/sirius-testnet-reset-wallets.rst
- Added a section on how to reset desktop wallet data.
- Linked to it from sirius testnet reset page.
> Add section on how to reset desktop wallet data

- source/mainnet/smart-contracts/references/schema-json.rst
An example had been split, causing confusion for readers.
Merge empty into enum section to make example clearer for users. Added cross reference to enum in Empty.
Closes #512
> Fix schema json topic

- source/mainnet/smart-contracts/references/crypto-primitives.rst
- source/mainnet/smart-contracts/references/host-fns.rst
- source/mainnet/smart-contracts/references/index.rst
Add reference for cryptographic primitives in V1 contracts.
Closes https://github.com/Concordium/concordium-rust-smart-contracts/issues/117
- Add reference page to make it them discoverable.
- Add host functions reference.
> Add basic reference to cryptographic primitives.

- source/mainnet/net/concepts/concepts-delegation.rst
- source/mainnet/net/snippets/delegation-faq.rst
Management wants the commission rates for passive delegation added to the documentation.
Added the rates to the concept topic.
> Add commission rates for passive delegation to documentation

- source/mainnet/net/installation/downloads-testnet.rst
Add installation instructions for concordium client on mac now that it is a package instead of a zip.
I've only added it to testnet as I assume we will be releasing that first.
**Note that the download link must be updated before publishing.**
Closes https://github.com/Concordium/concordium-node/issues/404
- Add install instructions to concordium client for mac on testnet
> Add installation instructions for the mac client

- source/mainnet/net/guides/run-node.rst
Make it easier to change ports in the docker configurations.
> Clarify the port mapping in the example configuration file.

- source/mainnet/net/guides/run-node.rst
The migration documentation is missing the migration steps for a existing baker node
Its not clear in the migration documentation how to continue to be a baker when you migrate your existing docker baker setup. If you dont double check, its very easy to miss that the new node isnt a baker.
Information on how to include environment variable activating the baker credentials.
> Update migration notes to include baker details

- source/mainnet/smart-contracts/tutorials/piggy-bank/testing.rst
You get a compiling error saying the function TestHost::new() should take 2 arguments, but it takes only 1. 
The error is fixed now.
Added second argument "TestStateBuilder::new()"  to the function TestHost::new().
> fixed an issue in TestHost::new() arguments

- source/mainnet/smart-contracts/guides/fallback-entrypoints.rst
- source/mainnet/smart-contracts/tutorials/wCCD/wCCD-interacting.rst
- source/mainnet/smart-contracts/tutorials/wCCD/wCCD-introduction.rst
- protocol addresses were swapped around
- fallback function explanation link goes to the documentation now and not to the code
> Small fixes to the wCCD documentation

- source/mainnet/smart-contracts/guides/build-schema.rst
- source/mainnet/smart-contracts/guides/custom-errors.rst
- source/mainnet/smart-contracts/tutorials/piggy-bank/testing.rst
Add information about error schemas and fix example code
- Explain why deriving `Reject` now requires `Serial`
- Remove warning about deriving reject on enums with fields
- Fix examples
> Add information about error schemas

- source/mainnet/net/guides/run-node.rst
- source/mainnet/net/installation/downloads-testnet.rst
- source/mainnet/net/installation/downloads.rst
Add pull-policy since we use the `latest` tag in the example. This will make docker check whether there is a newer version.
The users are still encouraged to use specific tagged versions.
> Add the pull-policy option.

- source/mainnet/net/guides/become-baker.rst
Corrected concordium-client command for `baker add`.
`-- keys-in` is obsolete
`-- keys-out` should be `--out`
> Corrected concordium-client command for `baker add`

- source/mainnet/net/installation/downloads-testnet.rst
- source/mainnet/net/installation/downloads.rst
- source/mainnet/net/references/concordium-client.rst
- source/mainnet/variables.rst
Inform users they need to run a command when they have downloaded the Linux version of Concordium Client to make the file executable.
Added to downloads pages. On the testnet page I cannot remove the extra line space because Sphinx does not like it if there is not a blank line after the bullet. And because it is variable text and not regular text I have to put in a pipe to force space. Otherwise the text for the addition is jammed up against the checksum.
Also minor corrections to concordium client topic.
> Update downloads with command to run in Linux

- source/mainnet/net/resources/bw-licenses.rst
- source/mainnet/net/resources/legal.rst
Add license attributions page for the browser wallet. Matches the about page link inside the browser wallet.
> Add license attributions page for BW

- source/mainnet/net/guides/run-node-windows.rst
Fix a typo in the testnet catchup URL in the Windows docs and switch to using environment variables over command line arguments.
> Fix a typo in the testnet catchup URL

- source/mainnet/net/installation/downloads-testnet.rst
- source/mainnet/net/installation/downloads.rst
- source/mainnet/net/resources/release-notes-mainnet.rst
- source/mainnet/net/resources/release-notes.rst
- source/mainnet/smart-contracts/guides/setup-contract.rst
closes #610 
document `cargo concordium init` command
**Note:** This documentation should be published after https://github.com/Concordium/concordium-smart-contract-tools/pull/7 is merged and a new cargo-concordium version 2.2.0 is released.
> Add cargo concordium init documentation

- source/mainnet/net/guides/company-identities.rst
We had to re-upload the mac distribution due to an issue with signing. So the hash has changed.
> Fix the hash of enterprise-id tools.

- source/mainnet/smart-contracts/guides/compile-module.rst
- source/mainnet/smart-contracts/guides/local-simulate.rst
- source/mainnet/smart-contracts/guides/setup-contract.rst
closes #630 
Note: This should be merged after [this](https://github.com/Concordium/concordium-rust-smart-contracts/pull/180) is merged.
- Created a READ.me file in the template folder and linked to it in this documentation (https://github.com/Concordium/concordium-rust-smart-contracts/pull/180). This READ.me includes additional information on the content of the templates and which part of the templates should be customized (e.g. the state of the default template or the logic of the receive function of the default template). 
Several gifs were also added to show what people can do after generating a smart contract project from these templates (e.g. how to test, compile, and simulate an invoke).
- Added additional info to the `compile-module.rst` file about where the user can find the …
> Add template improvements

- source/mainnet/net/desktop-wallet/install-ledger-app.rst
- source/mainnet/net/installation/downloads-testnet.rst
- source/mainnet/net/installation/downloads.rst
Add ledger app for the new 1.0.4 firmware version of the nanos+.
> Add ledger app for 1.0.4 firmware version of nanosplus

- source/mainnet/net/installation/downloads.rst
- source/mainnet/net/resources/release-notes-mainnet.rst
- source/mainnet/variables.rst
Inform users of mainnet node release on 29 November 2022
Update release notes, downloads, checksum
> Mainnet node release Nov 2022

- source/mainnet/net/guides/gitcoin-hackathon.rst
This page is hidden from the general documentation table of content but can be accessed as follows:
It summarized the information that needs to be conveyed to hackathon participants.
http://localhost:8000/net/guides/gitcoin-hackathon.html
> Fill page for gitcoin hackathon

- source/mainnet/net/desktop-wallet/install-ledger-app.rst
- source/mainnet/net/installation/downloads.rst
- source/mainnet/variables.rst
Display the certificate's public key on the website, so the user can confirm it when adding the certificate to their device.
Small adjustments to the ledger install guide. 
> Add Concordium's certificate's public key to the the ledger app install guide/download page

- source/mainnet/net/references/grpc2.rst
Inform users that Rosetta now supports grpc v2.
Add Rosetta to list of SDKs migrated to grpc v2.
> Add Rosetta to list of supported SDKs for grpc2

- source/mainnet/smart-contracts/guides/integration-test-contract.rst
- source/mainnet/smart-contracts/tutorials/piggy-bank/testing.rst
The imports in the examples are invalid. They should use underscores instead of dashes.
- Replace `-` with `_` in imports
> Fix imports of testing lib in examples

- source/mainnet/net/guides/dapp-examples.rst
- source/mainnet/smart-contracts/onboarding-guide-ethereum-developers/faq.rst
- source/mainnet/smart-contracts/onboarding-guide-solana-developers/faq.rst
- source/mainnet/smart-contracts/tutorials/wCCD/wCCD-full-dApp.rst
- source/mainnet/smart-contracts/tutorials/wCCD/wCCD-introduction.rst
- source/mainnet/variables.rst
- Add the canonical smart contract index for wCCD to the documentation. Update front-end URLs that link to the mainnet wCCD front end.
Note: This should be only merged once the wCCD front end for mainnet is deployed.
> Add documentation for wCCD

- source/mainnet/net/guides/run-local-chain.rst
Address and port had documentation switch around.
The `genesis.dat` file was mentioned to be moved earlier in docs but old location references in docker compose file.
Due to the movement of file only the data directory ‘local-0’ needs to be mounted.
> Minor corrections

- source/mainnet/smart-contracts/tutorials/setup-env.rst
Removed suffix `.js`
Removed suffix since name isn’t related to files.
> Update import statement for keys

- .github/workflows/deploy-preview.yml
- .github/workflows/deploy.yml
- .github/workflows/remove-preview.yml
- .gitignore
- README.md
- scripts/build.sh
Deploy Concordium Academy together with the developer documentation.
This will make the Deploy action also build and deploy Concordium Academy.
Likewise, adding preview label causes a preview of Concordium Academy to be built.
- Simplify build script and add Concordium academy.
- Make the 'Deploy' action include deployment of Concordium Academy.
- Generated and added keys to allow for deployment to https://github.com/Concordium/concordium-academy
> Add concordium academy when deploying

- source/_static/css/style.css
Since documentation is text-heavy, I think it would benefit from bigger font size and a font color slightly lighter than black.
**Before**
**After**
> Adjust font settings

- source/mainnet/smart-contracts/tutorials/piggy-bank/testing.rst
Fix some typos in the PyggyBank testing tutorial.
> Fix typos in PyggyBank tutorial

- source/mainnet/smart-contracts/tutorials/voting/voting-dapp.rst
- source/mainnet/smart-contracts/tutorials/wCCD/wCCD-front-end-set-up.rst
JSON RPC is deprecated (or nearly so) and references should be removed.
Front-end setup for wCCD and voting in tutorials.
> Remove references to JSON-RPC in documentation

- source/mainnet/net/release-notes/release-notes-lp.rst
1.2.0 release date still said September.
Changed to October
> Correct iOS 1.2.0 release date

- source/mainnet/net/installation/downloads.rst
- source/mainnet/net/release-notes/release-notes-lp.rst
- source/mainnet/variables.rst
Inform users about 6.1.7 Testnet release
Downloads
Variables
Release notes
> 6.1.7 Testnet release

- .github/workflows/deploy.yml
The Github action we use for deploying to academy, seems to not support deploy keys.
This will replace the action with another implementation claiming to support this.
> For academy: use deploy action supporting deploy keys

- .github/workflows/deploy.yml
- README.md
- public/robots.txt
- scripts/build.sh
Remove Academy deployment, since this is now a workflow in `concordium-academy` repo.
- Remove steps to deploy academy site from the Deploy workflow.
- Update deployment section of readme.md.
- Disallow web-crawlers from the academy previews.
> Moved Deploy academy to workflow in concordium-academy repo

- source/mainnet/net/desktop-wallet/accounts-desktop.rst
- source/mainnet/net/guides/become-baker.rst
- source/mainnet/net/guides/overview-desktop.rst
- source/mainnet/net/guides/run-node-macos.rst
- source/mainnet/net/guides/run-node-windows.rst
- source/mainnet/net/guides/run-node.rst
- source/mainnet/net/installation/previous-node-downloads.rst
- source/mainnet/net/nodes/node-runner-service-configuration.rst
Fixing an open support issue where a user was trying to use the old grpc port number.
Remove or change references to the old grpc port numbers
> Remove stray instances of old grpc port numbers

- requirements.txt
- source/mainnet/net/guides/gallery/gallery-frontend.rst
Fix dependabot warnings
Address all dependabot warnings and update requirements.txt.
> Update requirements.txt for dependabot warnings

- source/mainnet/conf.py
- source/mainnet/net/web3-id/concordia.rst
Add a link to the Discord Concordia bot in the documentation.
(Fix unrelated issue in conf.py)
Add link to the Concordia bot for Discord in concordia.rst
> Add link to discord bot in Concordia

- Pipfile
The jobs are currently failing due to a mismatch in Python versions.
The reason is that we implicitly use the latest `sphinxdoc/sphinx` image while relying on a specific version of Python being available. It might be a good idea to pin the docker image versions to avoid surprises like this in the future.
> Fix broken CI

- source/mainnet/net/voting/voting.rst
Promote cryptoX as the recommended option for voting with file backup based wallet.
Closes #1010
> Explain migration flow from mw-gen1 to cryptox in voting doc

- README.md
- source/mainnet/net/release-notes/release-notes-lp.rst
> BW 1.5.2 release

- source/mainnet/net/release-notes/release-notes-lp.rst
Add release notes for Concordium mobile wallets shielding removal update.
- Add Android legacy wallet 3.3.0 release notes
- Add Android phrase wallet 1.6.0 release notes
- Fix CryptoX release notes dropdown
> Concordium mobile shielding removal releases

- source/academy/tutorials/fractionalized-nft/smart-contract.rst
- source/academy/tutorials/nft-minting-w-id/minting-sc.rst
- source/mainnet/smart-contracts/tutorials/fungible-tokens/smart-contract.rst
- source/mainnet/smart-contracts/tutorials/sft-minting/build-smart-contract.rst
closes #1039 
- Remove `StateClone`
> Remove StateClone

- source/mainnet/net/release-notes/release-notes-lp.rst
Add CryptoX 1.2.0 for Android
- Add CryptoX 1.2.0 for Android
- Fix incorrectly rendered dropdown
> Add CryptoX 1.2.0 for Android

- source/mainnet/net/installation/downloads.rst
- source/mainnet/net/release-notes/release-notes-lp.rst
- source/mainnet/variables.rst
Release node version 7.0.5 for mainnet.
Update release notes, download links and variables.
> Mainnet 7.0.5 release.

- source/mainnet/smart-contracts/tutorials/piggy-bank/testing.rst
There were some errors in the code snippets in the tutorial
[Linear issue link](https://linear.app/concordium/issue/DOC-276/code-mistakes-in-piggybank-tutorial)
This wrong import was removed: use piggy_bank_part2::*;
This wrong function call: create_chain_and_contract(); was replaced with the correct setup_chain_and_contract();
Missing comma was added in this assert, after Some(insert_amount):
assert_eq!(
chain.contract_balance(initialization.contract_address),
Some(insert_amount),
"Piggy bank balance does not match amount inserted"
);
> Fixed code snippets errors and wrong import

- source/mainnet/tutorials/voting/voting-dapp.rst
- source/mainnet/tutorials/voting/voting-sc.rst
Improve the voting tutorial
- Removed wallet tutorial section, as it was already pointing to the existing, separate guide for connecting a wallet
- The `concordium-std` library is included automatically when using the `init` command, so that is now reflected in the tutorial
- Clarified that tests do exist on github, but are not explained in the tutorial
> Imporved voting tutorial, removed unnecessary wallet info

- source/mainnet/net/release-notes/release-notes-lp.rst
Adding release note for CryptoX for iOS 2.0.1
Added release note to documentation.
> Added release note for CryptoX for iOS v. 2.0.1

- source/_static/css/custom.css
Fix logo overapping menu button on mobile and wrong width.
Screenshot before: 
Screenshot after fix: 
1. Fix the overlapping issue by changing the logo container positioning to relative
2. Make the logo more responsive on mobile by constraining its width
3. Add space for the menu button on mobile devices
> Fixed logo position and width on mobile

- source/mainnet/docs/network/baker-pool.rst
Review and, if necessary, update, the `Validator management` article. Small changes were needed.
Corresponding linear ticket: [DOC-281](https://linear.app/concordium/issue/DOC-281/review-validator-management)
- clarified the `Mainnet status page` subscription process, it seemed outdated
- mentioned to read the `release information on Discourse` page, not subscribe, as there is no way to subscribe to it
- added references to `CCDScan` URL, as before only a reference to an internal article about it was present; kept the reference to the documentation article as well
> Reviewed and updated Validator management article

- source/mainnet/conf.py
Fix the redirect links
After manually checking html files generated, it seemed the best idea to add `en/mainnet` in front of the links.
> Fixed redirects by modifying conf

- source/mainnet/conf.py
Try to fix redirects, again, cannot be properly tested on `localhost`
Try witout `./` in front of the original link
> Try a different fix for redirects

- source/mainnet/conf.py
Fix redirect for links from buttons from the concordium website;
Also fixed 2 more links;
problem was the following:
- when you use ./ is front, it's an absolute path, everything coming after https://developer.concordium.software/
- when not, it's relative, meaning everything after https://developer.concordium.software/en/mainnet/
- this goes both for the link you're redirecting from and the link you're redirecting to
- before, there was no need to differentiate as most paths were the similar, now, with the new structure, we need to see which need a relative path and which need an absolute path
- link: …
> Fix redirect for buttons from the concordium website

- source/mainnet/conf.py
Small typo was present in my last PR:
https://github.com/Concordium/concordium.github.io/pull/1163
Fix the typo
> Fix last redirect, typo was there before

- source/mainnet/docs/smart-contracts/introduction.rst
- source/mainnet/tools/developer-page.rst
Review and update Docs Smart Contracts section.
- section about smart contract tools was in `DOCS`, it should be in `TOOLS` and was moved and replaced with a reference
> Move sc tools section from docs to tools

- source/mainnet/docs/smart-contracts/guides/quick-start.rst
The purpose of the pull request is to remove any links or references to the legacy wallets in the documentation section Docs/Smart Contracts.
In "Concordium smart contracts quick start guide" step 3 "Set up a Concordium Wallet": Removed links to setup-mobile-wallet - both for gen1 and gen2 and replaced with link to setup-cryptox-wallet. Also updated text in step 3 accordingly.
> Removed ref to legacy wallets and inserted ref to cryptox

- source/_static/css/custom.css
- source/_static/css/style.css
- source/_static/css/tippy.css
- source/_templates/navbar-logo.html
- source/mainnet/conf.py
Feature - enable dark mode WIP
Not complete:
- need to decide whether to keep button toggle or just to use auto mode and take the system theme
- default mode will be "light" for now, then "auto" when feature is complete
- navbar and logo still have a slight color gradient difference:
Above problems were fixed, now it looks good, only need to decide if we keep the button toggle: 
- add dark theme in `conf.py`
- adapt css for dark theme
> Added dark mode toggle and adapted css, WIP

- source/mainnet/docs/smart-contracts/contract-schema.rst
There was a github link pointing to an archived repository
- changed link to point to the new repo
> Changed repo link to new one

- source/mainnet/docs/smart-contracts/best-practices/costs.rst
- source/mainnet/docs/smart-contracts/guides/build-schema.rst
- source/mainnet/docs/smart-contracts/guides/compile-module.rst
- source/mainnet/docs/smart-contracts/guides/fallback-entrypoints.rst
- source/mainnet/docs/smart-contracts/guides/json-params.rst
- source/mainnet/docs/smart-contracts/guides/no-std.rst
- source/mainnet/docs/smart-contracts/guides/setup-contract.rst
Finished review of the Build section in Smart Contracts  according to the DOC-301 ticket
- removed mention of `dalloc` and replaced with a reference to `bump_alloc`, which is the latest recommended custom allocator
- added a note in the `Use a custom allocator` article mentioning to the user to be careful in the use of `bump_alloc`, with an example
- added references to `cargo-concordium` rust crate documentation
- replaced a reference to `build-contract` with a reference to `setup-env`, which is the main tutorial for installing dev tools
- added a reference in `JSON parameters` to a related guide on how to use them
- link: …
> Sc review build

- source/mainnet/docs/guides/address-book.rst
- source/mainnet/docs/guides/change-account-name.rst
- source/mainnet/docs/guides/change-identity-name.rst
- source/mainnet/docs/guides/create-account.rst
- source/mainnet/docs/guides/create-identity.rst
- source/mainnet/docs/guides/export-import.rst
- source/mainnet/docs/guides/recover-wallet.rst
- source/mainnet/docs/guides/recovery.rst
- source/mainnet/docs/mobile-wallet/change-passcode-mw.rst
The purpose of the pull request is to remove any description of or reference to the legacy wallets in pages under the Wallet activities section.
The following pages were updated:
- Create an identity
- Change identity name
- Create an account
- Change account name
- Make a backup
- Recover wallet
- Update passcode and biometrics
- Manage address book
> Removed legacy wallets from wallet activities section

- source/mainnet/docs/installation/downloads.rst
The purpose of the pull request is to delete the legacy wallets from the Downloads page.
Deleted legacy wallet sections on Downloads page.
> Removed legacy wallets from the Downloads page

- Pipfile
- Pipfile.lock
- source/mainnet/conf.py
Implement sitemap.
- use and configure sphinx-sitemap extension
> Use sitemap extension

- README.md
Fixing link to Concordium Style Guide in readme file.
> Updated link to style guide in readme

- source/mainnet/docs/network/guides/baker-docker.rst
- source/mainnet/docs/network/guides/become-baker.rst
Update the [validation with concordium-client](https://docs.concordium.com/en/mainnet/docs/network/guides/become-baker.html#create-and-register-validator-keys) article
- replace `--out` with `--validator-credentials-out` according to [concordium-client 7.0.1 release notes](https://github.com/Concordium/concordium-client/releases) 
- remove mentions of deprecated wallets
- replace running a node reference with correct one
- remove outdated recommendation to keep the key output file name as ``validator-credentials.json``
- removed confusing duplicate command
- added reference to article for importing validator key to node config
- link: …
> Update client validation article

- source/mainnet/docs/index.rst
- source/mainnet/docs/protocol/concordium-protocol.rst
- source/mainnet/docs/resources/glossary.rst
New page with high-level information about the Concordium protocol.
Added the page and updated the Glossary 
- [x I have performed a self-review of the changes.
> Add what is the concordium protocol doc

- source/mainnet/docs/installation/downloads.rst
- source/mainnet/docs/installation/previous-node-downloads.rst
- source/mainnet/docs/release-notes/release-notes-lp.rst
- source/mainnet/variables.rst
Release node version 8.0.3 for testnet.
- Download links
- Hashes
- Release notes
- Old download links.
> Download links and release notes for 8.0.3 node.

- source/mainnet/docs/installation/downloads.rst
- source/mainnet/docs/installation/previous-node-downloads.rst
- source/mainnet/docs/release-notes/release-notes-lp.rst
- source/mainnet/variables.rst
Release node version 8.0.3 for mainnet.
- Update release notes.
- Update download links.
- Update checksum.
- Update old download links.
> Release node 8.0.3 for mainnet.

- source/mainnet/docs/index.rst
- source/mainnet/docs/smart-contracts/guides/build-contract.rst
- source/shared/setup-env.rst
- `cargo-concordium` version 4.1.0 got yanked on `crates.io` and should not be used.
https://crates.io/crates/cargo-concordium/versions
- Update comments to use version 4.1.1
> Update cargo concordium version

- source/mainnet/conf.py
- source/mainnet/docs/network/guides/create-proofs.rst
- source/mainnet/docs/network/web3-id/concordia.rst
- source/mainnet/docs/network/web3-id/index.rst
To add a page explaining that Concordia bot is offline, but the code is open source and available via link on page.
- Added new concordia.rst page (the earlier page was removed)
- Updated conf.py (removed earlier added redirect since the new explainer page has the same address as the old concordia page)
- [x ] My code follows the style of this project.
- [x ] The code compiles without warnings.
> added new Concordia page with explainer

- source/mainnet/docs/desktop-wallet/install-ledger-app.rst
This updates the download links for the governance ledger app, as well as the version number (1.0.0 to 1.1.0).
> Update the download links for governance ledger app

- source/mainnet/docs/index.rst
- source/mainnet/docs/protocol/consensus-mechanisms.rst
- source/mainnet/docs/resources/glossary.rst
To add a page with high-level information on consensus mechanisms linking it to the more detailed pages about validation and delegation.
- Added the page Consensus mechanisms
- Added links and mouse-over text with concept explanations
- Added more concepts and explanations to the glossary
> Add consensus mechanisms page to documentation

- source/mainnet/docs/network/guides/create-proofs.rst
https://concordium.slack.com/archives/C03DRCC9GR1/p1743014600943049
Remove link that used to open the backend verifier endpoints in the browser that often caused confusion to readers because they thought the `link/service` was broken.
> Remove link that would open verifier backend endpoints in browser

- source/mainnet/docs/network/web3-id/identity-provider-interfaces.rst
- source/mainnet/docs/network/web3-id/index.rst
Add guide about Identity provider interfaces.
> Add guide for idp interfaces

- source/mainnet/docs/installation/downloads.rst
- source/mainnet/docs/release-notes/release-notes-lp.rst
- source/mainnet/variables.rst
> Update documentation with release of desktop wallet 1.8.1 (mainnet)

- source/mainnet/docs/desktop-wallet/install-ledger-app.rst
- source/mainnet/docs/guides/setup-wallets-lp.rst
Update the docs to include instructions for how to install the latest version of the governance ledger app for both ledger nano s/s+.
Took the liberty to also group content by OS and ledger device to make it easier for the reader to filter the content necessary to read.
> Governance ledger app/update installation steps
