source/testnet/references/query-node.rst
Updated links and references
Removed a mention of delegation in an example, besides that nothing is changed content wise.
=> Querying a node

source/_static/style.css, source/_templates/layout.html
Since we currently only have two items in the topbar and it is taking a lot of space.
Instead the items should be in the sidebar:
=> Move topbar navigation to sidebar

source/testnet/references/query-node.rst, source/testnet/see-also/troubleshooting.rst
Removed a mention of delegation and updated the troubleshooting page.
=> Small fixes

source/smart-contracts/general/contract-schema.rst, source/smart-contracts/general/develop-contracts.rst, source/smart-contracts/guides/build-schema.rst, source/smart-contracts/index.rst, source/smart-contracts/tutorials/piggy-bank/writing.rst, source/testnet/guides/accounts-transactions.rst, source/testnet/guides/become-baker.rst, source/testnet/guides/explore-more.rst, source/testnet/guides/get-started.rst, source/testnet/guides/get-the-app.rst, source/testnet/guides/run-node.rst, source/testnet/references/concordium-client.rst, source/testnet/references/id-accounts.rst, source/testnet/references/query-node.rst, source/testnet/references/transactions.rst, source/testnet/see-also/glossary.rst
Fixes most of the internal links except the ones in `downloads.rst`, which are be fixed by @jens-concordium in another branch.
=> Fix a bunch of internal links

source/smart-contracts/guides/setup-contract.rst, source/smart-contracts/references/host-fns.rst, source/testnet/see-also/glossary.rst
merge of typo fix into testnet4 branch
=> Glossary typo

source/smart-contracts/guides/custom-errors.rst, source/smart-contracts/guides/initialize-contract.rst, source/smart-contracts/index.rst, source/smart-contracts/tutorials/piggy-bank/testing.rst, source/smart-contracts/tutorials/piggy-bank/writing.rst, source/testnet/see-also/glossary.rst
- Update code examples
- Add guide about returning custom errors
- Minor cleanup
=> Reject reasons

README.md
=> Code of Conduct badge

source/index.rst, source/terms-and-conditions/index.rst, source/terms-and-conditions/mobile-wallet-tc.rst
We need a online version of the Mobile Wallet T&C. For now it has been added here.
Added a new page to the documentation, containing T&C.
=> Terms and conditions

source/testnet/concepts/concepts-baker.rst, source/testnet/guides/add-baker-desktop.rst, source/testnet/guides/become-baker.rst, source/testnet/index.rst, source/testnet/references/query-node.rst, source/testnet/resources/glossary.rst
Guide to adding a baker in the Desktop Wallet. Split up Become a baker into two topics.
=> Baker documentation - Desktop Wallet, Client and concept

source/testnet/desktop-wallet/create-account-desktop.rst, source/testnet/desktop-wallet/create-identity-desktop.rst, source/testnet/desktop-wallet/install-ledger-app.rst, source/testnet/index.rst
=> Ledger docs

source/_templates/index.html, source/_templates/layout.html
Hide outdated testnet4 documentation
- Redirect every page to an under-construction page.
=> Hide testnet4 docs

README.md
Describe how to contribute to the documentation after release of Mainnet
- Added a **Contributing** section in the README.
=> Add contributing section in readme

source/testnet/desktop-wallet/install-ledger-app.rst, source/testnet/guides/multi-credentials.rst, source/testnet/index.rst
Topic describing how to add credentials to an account and change the threshold
Added credentials topic
Small change til Ledger topic
Small change to index
=> multi credentials on account

README.md
The purpose is to be more clear about how the flow is for new features which are expected to end in the mainnet documentation.
- Added note in Contributing section in the README
=> Add note on contributing features which are compatible with mainnet

source/testnet/desktop-wallet/multisig-simple-transfer.rst, source/testnet/guides/add-baker-desktop.rst, source/testnet/guides/multi-credentials.rst, source/testnet/index.rst
New topic about multisig transfer without a schedule
Added new topic
Changed index
Updated paragraph about create and sign in more documents
=> multisig simple transfer topica added and new paragraph about signing

source/net/concepts/id-accounts.rst, source/net/desktop-wallet/create-account-desktop.rst, source/net/desktop-wallet/create-identity-desktop.rst, source/net/desktop-wallet/export-import-desktop.rst, source/net/desktop-wallet/get-started-desktop.rst, source/net/desktop-wallet/install-ledger-app.rst, source/net/guides/overview-baker-process.rst, source/net/guides/run-node-ubuntu.rst, source/net/index.rst, source/net/installation/downloads.rst, source/net/mobile-wallet/get-started.rst, source/net/references/manage-accounts.rst, source/net/references/transactions.rst
Describes how to export and import accounts, identities and addresses
Added new topic - export and import
Removed references to Concordium ID
Moved local table of contents
=> export and import and various links and naming updates

source/net/index.rst, source/net/resources/dw-licenses.rst
We needed to have a license disclaimer for the desktop wallet. This has been added in this PR.
A desktop wallet license page was added.
=> Added DW license page

README.md, scripts/build.sh
Enable deployment of mainnet documentation.
=> Add mainnet branch to build script

source/net/desktop-wallet/get-started-desktop.rst, source/net/desktop-wallet/install-ledger-app.rst, source/net/installation/downloads.rst
Information update
download link
Note
Ledger - Python3
=> Minor changes - link,notes

.github/workflows/lint.yml
Enable linting for push and PRs to mainnet
=> Enable linting on mainnet

source/_templates/index.html
Smart Contracts should be removed from splash screen, and the run a node section had to be changed a bit.
Smart contracts were removed from the splash screen, and the run a node section was updated.
=> Removed SC from splash, and changed links

source/net/desktop-wallet/accounts-desktop.rst, source/net/desktop-wallet/create-account-desktop.rst, source/net/desktop-wallet/send-gtu-single-desktop.rst, source/net/desktop-wallet/shield-gtu-desktop.rst, source/net/desktop-wallet/single-sign-schedule.rst, source/net/index.rst
Document tasks and information on accounts
Added new topics (Send, Transfer with schedule, Overview)
Made minor updates to existing topics
=> New account topics and minor updates

source/net/desktop-wallet/get-started-desktop.rst, source/net/guides/overview-desktop.rst, source/net/index.rst
Overview topic that describes overall steps of getting started with the Desktop Wallet.
Created new overview topic (with steps 1-4 from baker overview)
Renamed Ledger wallet to device
Updated index
=> Created new get started DTW topic from baker overview topic.

.github/workflows/lint.yml, source/net/desktop-wallet/accounts-desktop.rst, source/net/desktop-wallet/create-account-desktop.rst, source/net/desktop-wallet/get-started-desktop.rst, source/net/desktop-wallet/install-ledger-app.rst, source/net/desktop-wallet/send-gtu-single-desktop.rst, source/net/desktop-wallet/shield-gtu-desktop.rst, source/net/desktop-wallet/single-sign-schedule.rst, source/net/guides/overview-baker-process.rst, source/net/guides/overview-desktop.rst, source/net/index.rst, source/net/installation/downloads.rst
=> Sync mainnet with main branch

source/net/resources/release-notes-mainnet.rst
Correct spelling
spelling bulleted list
=> changed spelling error

source/net/guides/become-baker.rst, source/net/guides/run-node.rst
A couple of incorrect dashboard links were reported, this is the fix.
Updated links.
=> Updated dashboard links

source/net/guides/become-baker.rst
A link was missing https in a previous PR, for updated dashboard links
Https now added
=> Added https to a link

source/net/installation/downloads.rst
Advise about no support for M1
added line about no support for M1
=> note about MacBook air M1

source/net/guides/add-baker-desktop.rst
Changed various typos
Correct typos
_Describe the purpose of the pull request, link to issue describing the problem, etc.
Changed various typos
=> typos-baker

source/mainnet/_templates/index.html
A link to the Concordium main website was requested to be added to the splash screen, so the purpose is to add that.
A link to the main website was added below the feature box, and a link (to the doc splash screen) was added to the logo at the top of the page.
=> Added link to logo, and added link to main page on splash screen

source/mainnet/_templates/index.html
There was a request for changed wording on the splash screen:
Please replace "How to make an account" by "How to create an account"
Changed the wording as mentioned above.
=> Changed wording on splash screen

make.bat, source/mainnet/net/desktop-wallet/change-baker-stake.rst, source/mainnet/net/desktop-wallet/change-restake-settings.rst, source/mainnet/net/desktop-wallet/remove-baker.rst, source/mainnet/net/desktop-wallet/update-baker-keys.rst, source/mainnet/net/index.rst, source/shared/net/concepts/concepts-baker.rst, source/shared/net/desktop-wallet/change-baker-stake.rst, source/shared/net/desktop-wallet/change-restake-settings.rst, source/shared/net/desktop-wallet/remove-baker.rst, source/shared/net/desktop-wallet/update-baker-keys.rst, source/testnet/net/desktop-wallet/change-baker-stake.rst, source/testnet/net/desktop-wallet/change-restake-settings.rst, source/testnet/net/desktop-wallet/remove-baker.rst, source/testnet/net/desktop-wallet/update-baker-keys.rst, source/testnet/net/index.rst
Baker transactions documentation
Added topics:
Change baker stake
Change restake settings
Remove baker
Update baker keys
=> New baker topics, updated index and change to make.bat

source/mainnet/_templates/layout.html, source/shared/_static/style.css, source/shared/_templates/analytics.html, source/testnet/_templates/layout.html
Add analytics and a consent banner
=> Add Google analytics and consent banner

source/mainnet/_templates/index.html
The landing page is still missing analytics
- Add analytics to landing page
=> Add analytics to landing page

source/mainnet/net/desktop-wallet/sign-transaction.rst, source/mainnet/net/index.rst, source/shared/net/desktop-wallet/sign-transaction.rst, source/testnet/net/desktop-wallet/sign-transaction.rst, source/testnet/net/index.rst
Added topic describing how to sign a transaction
Added files
Updated indexes
=> Sign a transaction

source/mainnet/net/desktop-wallet/overview-addresses.rst, source/mainnet/net/desktop-wallet/proposed-transactions.rst, source/mainnet/net/desktop-wallet/settings-overview.rst, source/mainnet/net/index.rst, source/shared/net/desktop-wallet/get-started-desktop.rst, source/shared/net/desktop-wallet/overview-addresses.rst, source/shared/net/desktop-wallet/proposed-transactions.rst, source/shared/net/desktop-wallet/settings-overview.rst, source/testnet/net/desktop-wallet/overview-addresses.rst, source/testnet/net/desktop-wallet/proposed-transactions.rst, source/testnet/net/desktop-wallet/settings-overview.rst, source/testnet/net/index.rst
Topics describing various settings and overviews in the Desktop Wallet.
Added new topics: Settings, addresses, proposals
Updated indexes
=> Desktop overviews

source/testnet/net/installation/downloads.rst
The new Testnet builds of the mobile wallet were ready, so they needed to be online in the documentation.
Added links and descriptions on how to get the Testnet mobile wallets, to the Testnet download page.
=> Added Testnet options for mobile wallet

source/shared/net/desktop-wallet/install-ledger-app.rst
Describe that "broken certificate chain" should be ignored when installing the certificate.
Edited certificate installation description
Indented code examples
=> Ledger app installation edits

source/testnet/net/installation/downloads.rst
Testnet versions of the Desktop Wallet is now available, so these have been added to the Downloads page on the Testnet docs.
DW links were added to the Testnet Downloads page.
=> Added DW links to Testnet docs

source/mainnet/net/desktop-wallet/make-account-report.rst, source/mainnet/net/index.rst, source/shared/net/desktop-wallet/make-account-report.rst, source/testnet/net/desktop-wallet/make-account-report.rst, source/testnet/net/index.rst
Added topic about creating reports
Added topic with content to shared
Added topics with includes to mainnet and testnet
Updated mainnet and testnet index
=> make account report

source/mainnet/conf.py, source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/conf.py, source/testnet/net/resources/release-notes.rst
The Testnet release notes were out-dated, so these have been updated to match the current releases.
Testnet release notes were updated, and InterSphinx was added to enable references between Mainnet and Testnet.
=> Updated Testnet release notes and added InterSphinx

source/mainnet/net/installation/downloads.rst
Add a download link for the mainnet genesis block.
=> Add mainnet genesis block to the downloads page.

source/mainnet/net/desktop-wallet/send-shielded-amount.rst, source/mainnet/net/index.rst, source/shared/net/desktop-wallet/send-shielded-amount.rst, source/testnet/net/desktop-wallet/send-shielded-amount.rst, source/testnet/net/index.rst
Topic describing how to make shielded transfers
Added new topic to shared
Added topics with include to testnet and mainnet
Changed index for testnet and mainnet
=> how to make a shielded transfer

source/mainnet/net/desktop-wallet/create-credentials-file.rst, source/mainnet/net/guides/overview-shared-accounts.rst, source/mainnet/net/index.rst, source/shared/net/desktop-wallet/create-credentials-file.rst, source/shared/net/desktop-wallet/send-shielded-amount.rst, source/shared/net/guides/multi-credentials.rst, source/shared/net/guides/overview-shared-accounts.rst, source/testnet/net/desktop-wallet/create-credentials-file.rst, source/testnet/net/guides/overview-shared-accounts.rst, source/testnet/net/index.rst
Describe the process of sharing accounts and adding credentials
Overview of shared accounts with multiple credentials
Add credentials to an account
Create a credentials file
=> Topics about credentials and shared accounts

source/shared/net/desktop-wallet/create-identity-desktop.rst
Added a step that was missing.
Changed some descriptions and added a step.
=> Create identity edits

source/mainnet/net/installation/downloads.rst
Add checksums to the node package and genesis block downloads for validation.
=> Add SHA checksums to node and genesis block downloads.

source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/shared/net/desktop-wallet/create-credentials-file.rst, source/shared/net/desktop-wallet/multisig-simple-transfer.rst, source/shared/net/desktop-wallet/send-gtu-single-desktop.rst, source/shared/net/desktop-wallet/send-shielded-amount.rst, source/shared/net/desktop-wallet/shield-gtu-desktop.rst, source/shared/net/desktop-wallet/sign-transaction.rst, source/shared/net/desktop-wallet/single-sign-schedule.rst, source/shared/net/guides/add-baker-desktop.rst, source/shared/net/guides/multi-credentials.rst, source/shared/net/guides/multisig-transfer.rst, source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
To release version **1.1.5** of the desktop wallet by providing updated links to the new binaries.
- Updated download links.
- Removed disclaimers as both the macOS and Windows builds are now signed.
- Updated a bit of text in the guides where some text has been in the UI has been changed.
- Added a release note for the desktop wallet update.
=> Desktop wallet update 1.1.5

source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
Release 1.1.6 of the desktop wallet.
Updated download links and added a release note.
=> Add release 1.1.6 of the desktop wallet

source/mainnet/net/installation/downloads.rst, source/testnet/net/installation/downloads.rst
Remove disclaimers for Windows download as it is now available.
Removed disclaimers for the Windows download.
=> Removed download disclaimers for Windows

source/shared/net/desktop-wallet/proposed-transactions.rst
Add description of cancelled status to proposed transactions overview.
Added paragraph about cancelled status.
=> Added change to view transaction proposal

source/shared/net/guides/multisig-transfer.rst
Added more conceptual information to make the concept of scheduled transfers clearer to the users.
Added paragraph explaining how the transfer works.
Reorganized intro paragraphs.
Changed information in intro paragraphs.
=> Added more conceptual info about scheduled transfers.

source/shared/net/desktop-wallet/create-account-desktop.rst, source/shared/net/guides/run-node-ubuntu.rst, source/shared/net/mobile-wallet/accounts-transactions.rst, source/shared/net/mobile-wallet/get-started.rst
Make it easier to access youtube videos on how to use the Mobile Wallet and run a node
Added links to relevant topics
=> Added video links

source/mainnet/net/installation/downloads.rst, source/shared/net/desktop-wallet/accounts-desktop.rst, source/shared/net/desktop-wallet/change-restake-settings.rst, source/shared/net/desktop-wallet/create-account-desktop.rst, source/shared/net/desktop-wallet/create-credentials-file.rst, source/shared/net/desktop-wallet/multisig-simple-transfer.rst, source/shared/net/desktop-wallet/send-gtu-single-desktop.rst, source/shared/net/desktop-wallet/update-baker-keys.rst, source/testnet/net/installation/downloads.rst
Fix minor issues
Minor edit such as missing bold UI elements in a number of files.
=> Various minor changes

source/testnet/net/installation/downloads.rst
Updated structure of page, mainly to include the new native distributions and group them all together under node distributions.
- new maon node heading
- new Windows node
- new Mac node
- applied same format to mobile wallets with subheadings
- 
=> Updated structure as discussed

source/testnet/net/installation/downloads.rst
Links not working
Updated links
=> Changed links

source/mainnet/_templates/index.html
It was a bit difficult to find the status pages, so we discussed adding links to those, the dashboards, and support page, to the documentation landing page. 
Links were added at the bottom of the documentation landing page.
=> Added links to dashboards, status pages and support

source/testnet/net/guides/run-node-macos.rst, source/testnet/net/installation/downloads.rst
New links were needed for a range of signed software.
A note about installing Rosetta on M1 Macs was also needed.
Links were updated on the Downloads page, and Rosetta was mentioned on the Run a node on Mac guide.
=> Added links to signed software and a note about Rosetta on M1 Macs.

source/mainnet/_templates/index.html
Testnet links on landing page were not working, so they should be fixed. 
Links were fixed.
=> Link fixes

source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
Update links for the new release.
Bump versions in links.
=> Update download links for version 1.1.2.

source/testnet/net/installation/downloads.rst
Update distribution to match the node version for consistency.
=> Update the linux distribution link to match.

source/mainnet/net/guides/run-node-ubuntu.rst, source/testnet/net/guides/run-node-ubuntu.rst
Provide documentation for out of band catchup with debian packages.
=> Link to debian out of band catchup.

source/shared/net/desktop-wallet/install-ledger-app.rst
Describe how to update the Ledger app to the latest version.
Added sections on how to update the Ledger app for Windows, macOS, and Ubuntu.
=> Update Ledger app

source/testnet/net/installation/downloads.rst
Cargo-concordium download links on Testnet were outdated.
Download links were updated.
=> Updated cargo download links on Testnet

en/testnet/net/guides/run-node-ubuntu.html, en/testnet/net/installation/downloads.html
A dashboard link was dead and cargo download links were incorrect.
Fixed the links.
=> Fixed dashboard and cargo links

source/shared/net/desktop-wallet/transaction-log-filter.rst
Text on transaction log filter actions has changed, this updates the documentation to match the change in the destkop wallet
- Updated references to filter actions.
=> Updated to match text on filter actions in DTW

source/shared/net/desktop-wallet/install-ledger-app.rst
Change Ledger update information to include info on how to uninstall old version.
Changed update sections for Windows, macOS and Linux.
=> Changed update sections

source/shared/net/desktop-wallet/create-account-desktop.rst, source/shared/net/desktop-wallet/create-credentials-file.rst, source/shared/net/desktop-wallet/create-identity-desktop.rst, source/shared/net/desktop-wallet/send-gtu-single-desktop.rst, source/shared/net/desktop-wallet/send-shielded-amount.rst, source/shared/net/desktop-wallet/single-sign-schedule.rst, source/shared/net/guides/multi-credentials.rst, source/shared/net/guides/multisig-transfer.rst
Update topics with new Ledger terminology and add information about adding memos to transactions.
Updated procedures (both single and multi-signature transactions) with new terminology and memo description:
Simple transfers
Shielded transfers
Encrypted transfers
=> Ledger terminology and memo changes

source/mainnet/_templates/index.html
The Mainnet feature box needed to be updated a bit with new links.
Links to new "run-a-node" guides were added.
=> Added some more links to Mainnet box

source/mainnet/net/guides/run-node-ubuntu.rst, source/testnet/net/guides/run-node-ubuntu.rst
_mainnet upgrade to 1.1.3
-testnet upgrade from 1.0.1 to 1.1.2 and from 1.1.2 to 1.1.3
=> Upgrade node on Ubuntu

source/mainnet/net/resources/release-notes-mainnet.rst
A release note for the Oct 6th release was needed.
Release note was added to Mainnet docs.
=> Release for Oct 6th

source/mainnet/net/resources/release-notes-mainnet.rst
Added alpha centauri versioning.
Added Alpha centauri 1.0, 1.1, 1.2 and 2.0. 
=> added alpha centauri

source/mainnet/net/installation/downloads.rst, source/shared/net/guides/run-node.rst, source/testnet/net/installation/downloads.rst
Add upgrade instructions for the docker distribution.
=> Upgrade instructions for the docker distribution.

source/mainnet/net/guides/run-node-ubuntu.rst
Fix incorrect upgrade instructions for the mainnet ubuntu node.
=> Fix upgrade instructions for mainnet node.

source/mainnet/net/index.rst, source/mainnet/net/resources/terms-and-conditions-dw.rst, source/mainnet/net/resources/terms-and-conditions-mw.rst, source/shared/net/resources/terms-and-conditions-dw.rst, source/shared/net/resources/terms-and-conditions-mw.rst, source/testnet/net/index.rst, source/testnet/net/resources/terms-and-conditions-dw.rst, source/testnet/net/resources/terms-and-conditions-mw.rst
It was decided to host the T&C for mobile wallet and desktop wallet in the documentation, so they had to be added.
Added pages with T&C for MW and DW.
=> Added terms and conditions for MW and DW - Don't merge before MW release is ready

source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/net/resources/release-notes.rst
The new version of the Android mobile wallet will soon be released, so a set of release notes should be put out.
Release notes for the new version of the Android app has been added to both Mainnet and Testnet.
=> Added release notes for the next Android release - Don't merge or deploy before the app is ready.

source/testnet/net/installation/downloads.rst
The new version of the Android app is ready, so the download link needs to be updated.
Testnet download link was updated.
=> Updated Android testnet download link

source/shared/net/desktop-wallet/account-recovery.rst, source/shared/net/desktop-wallet/export-import-desktop.rst
_Make final review changes to backup topics
_Minor edits to Make a backup of identities, accounts, and addresses in the Desktop Wallet
=> Review changes of backup docs

source/shared/net/guides/deciding-wallet.rst
A list wasn't displayed correctly on the "Deciding wallet" page.
Fixed the list. 
=> Fixed layout error on deciding wallet page

source/mainnet/conf.py, source/testnet/conf.py
The target links for the newly added redirect pages didn't work. The purpose was to fix these broken links.
Fixed links.
=> Changed redirect links

source/shared/net/desktop-wallet/create-identity-desktop.rst, source/shared/net/references/manage-accounts.rst
_More identity providers will be added so the reference to Notabene as the only provider has been removed.
Removed mentioning of Notabene and wrote more general reference.
=> remove provider name

source/shared/net/resources/terms-and-conditions-dw.rst, source/shared/net/resources/terms-and-conditions-mw.rst
_Change date for Terms and Conditions
_Changed date for T&C for Mobile Wallet and Desktop Wallet
=> change date terms and conditions

source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
Updated release notes and download links for testnet
Updated release notes and download links for testnet
=> Testnet release

source/testnet/net/installation/downloads.rst
As the macOS and Windows installers will delete the current configuration, people should be made aware of it. 
Added a note on the above.
=> Added a note on backing up node configuration

source/shared/net/guides/add-baker-desktop.rst
=> Fix incorrect xref

source/shared/net/desktop-wallet/create-account-desktop.rst, source/shared/net/desktop-wallet/create-credentials-file.rst, source/shared/net/desktop-wallet/create-identity-desktop.rst, source/shared/net/desktop-wallet/install-ledger-app.rst, source/shared/net/guides/multi-credentials.rst
User has to accept actions with the PRF-key or IdCredSec
On Windows, the user has to restart computer after installing Python and Pip
Updated 5 topics with additional Ledger information
=> ledger changes

source/mainnet/net/guides/run-node-ubuntu.rst, source/shared/net/guides/run-node.rst, source/testnet/net/guides/run-node-ubuntu.rst
Add information about grpc port is 10001 on testnet.
Changed 3 topics: Run a node with Docker, and Run a node with Ubuntu (testnet doc and mainnet doc)
=> grpc port edits

source/testnet/net/resources/release-notes.rst
We are releasing a new version of the iOS mobile wallet on Testnet. These are the release notes for the new version.
The release notes were added.
=> Added release notes for the new iOS wallet version

source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/net/resources/release-notes.rst
We are releasing the new iOS MW, which needs release notes.
iOS release notes added and a missing newline was added to testnet release notes.
=> Added iOS r-notes for Mainnet and fixed layout in testnet release notes

source/mainnet/net/guides/enterprise-identities.rst, source/mainnet/net/index.rst
Describes the main steps involved in creating an enterprise identity with links to additional information and downloads.
Added new topic to the mainnet documentation. 
Added topic to index.
=> Desribes how to create an enterprise identity.

source/shared/net/desktop-wallet/get-started-desktop.rst
To inform readers about Virtual Hive node in Desktop Wallet.
Added a sentence to step 4 about the Virtual Hive node being the default.
- [ X] I accept the above linked CLA.
=> Update to dw get started topic for virtual hive

source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/variables.rst, source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
Add release notes for the upcoming desktop wallet release (1.3.0)
=> Added release notes for desktop wallet 1.3.0

source/mainnet/net/resources/release-notes-mainnet.rst
There was a typo in the release notes
Fixed the typo. Concordrium --> Concordium
=> Fixed a typo

source/shared/net/mobile-wallet/create-identity.rst, source/shared/net/mobile-wallet/export-import-mw.rst, source/shared/net/mobile-wallet/setup-mobile-wallet.rst
It was decided to add more clear warnings and a video about backing up keys in the mobile wallet.
The clearer warning and video was added.
=> Backup warning

source/shared/net/resources/glossary.rst
Correct a mistake about the requirement for becoming a finalizer.
Correct the phrase, so it matches reality.
Used same phrasing as seen in https://developer.concordium.software/en/mainnet/net/guides/become-baker.html#finalization
=> Correct finalizer requirement

source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
The new version 3.0.1 of the node required release notes, new download links and new sha256 sums.
The release notes, links and shasums were added / updated.
=> Release notes node301 testnet

source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/variables.rst
Release 3.0.1 node version on Mainnet
Updated mainnet variables file, release notes, and downloads topic.
- [ X] My code follows the style of this project.
- [X ] The code compiles without warnings.
- [ X] I have performed a self-review of the changes.
- [X ] I accept the above linked CLA.
=> Updates for 301 node release on Mainnet

source/mainnet/conf.py, source/mainnet/net/installation/cdw-verification-instructions/cdw-appimage.rst, source/mainnet/net/installation/cdw-verification-instructions/cdw-deb.rst, source/mainnet/net/installation/cdw-verification-instructions/cdw-rpm.rst
Update broken links for desktop wallet signatures.
Update example commands to check signatures (because the old one didn't work)
=> update desktop wallet signatures + update instructions for checking them

source/mainnet/net/guides/run-node-ubuntu.rst, source/shared/net/guides/run-node-macos.rst, source/shared/net/guides/run-node-windows.rst, source/testnet/net/guides/run-node-ubuntu.rst
To clarify for users about opening up port 8888 on firewall to enable more connections.
Added text from Docker topic to Windows, macOS, and Ubuntu topics.
- [X ] My code follows the style of this project.
- [X ] The code compiles without warnings.
- [X ] I have performed a self-review of the changes.
- [ X] I accept the above linked CLA.
=> Added Enabling inbound connections text to topics.

source/mainnet/_templates/index.html, source/shared/net/mobile-wallet/create-account-mw.rst, source/shared/net/mobile-wallet/create-identity.rst, source/shared/net/mobile-wallet/export-import-mw.rst, source/shared/net/mobile-wallet/setup-mobile-wallet.rst, source/shared/net/snippets/backups.rst, source/shared/net/snippets/transaction-fees.rst
To make information about backups more available and clear.
Update to landing page, all topics that describe a backup.
=> Updates about backups

source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
To prepare documentation for release of DW v131 on Testnet.
Updated release notes, downloads with correct text, eventual links and checksums.
=> DW v131 on testnet

source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/net/resources/release-notes.rst
To inform users about release of updated Mobile Wallet for iOS.
Updated both testnet and mainnet release  notes with relevant information.
=> release notes updates for v33 release

source/mainnet/net/guides/run-node-ubuntu.rst, source/mainnet/net/index.rst, source/mainnet/net/nodes/docker.rst, source/mainnet/net/nodes/macos.rst, source/mainnet/net/nodes/troubleshoot-docker.rst, source/mainnet/net/nodes/troubleshoot-macos.rst, source/mainnet/net/nodes/troubleshoot-ubuntu.rst, source/mainnet/net/nodes/troubleshoot-windows.rst, source/mainnet/net/nodes/ubuntu.rst, source/mainnet/net/nodes/windows.rst, source/shared/net/guides/run-node-macos.rst, source/shared/net/guides/run-node-windows.rst, source/shared/net/guides/run-node.rst, source/shared/net/nodes/troubleshoot-docker.rst, source/shared/net/nodes/troubleshoot-macos.rst, source/shared/net/nodes/troubleshoot-ubuntu.rst, source/shared/net/nodes/troubleshoot-windows.rst, source/testnet/net/guides/run-node-ubuntu.rst, source/testnet/net/index.rst, source/testnet/net/nodes/docker.rst, source/testnet/net/nodes/macos.rst, source/testnet/net/nodes/troubleshoot-docker.rst, source/testnet/net/nodes/troubleshoot-macos.rst, source/testnet/net/nodes/troubleshoot-ubuntu.rst, source/testnet/net/nodes/troubleshoot-windows.rst, source/testnet/net/nodes/ubuntu.rst, source/testnet/net/nodes/windows.rst
To update the information we have about nodes to be more specific and versionless about upgrades and to include troubleshooting information per platform.
Updated existing Run a node topics to include upgrade info. Added topics for troubleshooting (with the idea that these will grow over time). Created necessary TOC structure topics and edited indexes to include those.
=> Node upgrade made versionless, added troubleshooting info all platforms

source/shared/net/desktop-wallet/get-started-desktop.rst
To incorporate the recommended change from joesixpack.
Updated the text in the first bullet of prerequisites to state that you should connect to a trusted node. Removed suggested link to it being an Ubuntu node since you can run a node on multiple platforms as it states further along in the paragraph.
=> Updated prerequisites text.

source/shared/net/desktop-wallet/install-ledger-app.rst
To simplify and clarify the ledger install instructions for macOS.
Closes #397.
Added steps describing how to navigate to a directory in Terminal; combined dependency installation steps into one step.
=> Updated macos ledger install steps.

source/shared/net/guides/run-node-macos.rst, source/shared/net/nodes/troubleshoot-macos.rst
Related to PR 402, this PR adds corrections to the macOS node files.
Updates to code lines in troubleshooting. Fix some strange artifacts in the install and upgrade section of text.
=> Corrections to macOS files after review.

source/shared/net/guides/become-baker.rst, source/shared/net/references/transactions.rst
To inform the user how to use the baker set-keys transaction in Concordium client.
Added section about updating baker keys. Other minor updates in the topic. Updated the concordium client transactions table with cross reference to the Become a baker using Concordium client topic.
Closes #197
=> Add baker set key to concordium client topic. Update transactions table.

source/mainnet/net/installation/downloads.rst, source/testnet/net/installation/downloads.rst
To make it clear to the user which version of the software he is downloading, versions are added to the downloads page.
Added version numbers (usually in title) to downloads pages for both testnet and mainnet.
Closes #299
=> Versions added to downloads page

source/shared/smart-contracts/tutorials/piggy-bank/index.rst, source/shared/smart-contracts/tutorials/piggy-bank/testing.rst, source/shared/smart-contracts/tutorials/piggy-bank/writing.rst
Make sure that users understand that they need to have a node and account in order to be able to create and test smart contracts.
Added cross references to preparation section for both writing and testing files. Cleaned up use of royal "we" in both topics, also many comma splices.
Closes #403
=> Added cross references, cleaned up language.

source/shared/net/desktop-wallet/install-ledger-app.rst
User was overwhelmed about Homebrew installation, needed clarification.
Added hyperlinks to some tools. Split step.
=> Clarify some tools in Ledger macOS setup

source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/net/resources/release-notes.rst
To inform users about v1.3(34) Mobile Wallet for iOS release.
Added information about release to release notes for testnet and mainnet.
=> Updated testnet and mainnet release notes for iOS wallet update.

source/mainnet/conf.py, source/testnet/conf.py
The copyright date was not up to date for either mainnet or testnet.
Updated conf.py for both mainnet and testnet to include copyright range.
=> Updated copyright date in footer

README.md
Added two more documentation style guides and additional information about second person and imperative.
After finding a lot of "we" and long, complicated sentences, I thought it was necessary to add some more information to the readme, particularly the style guide section.
Added two more documentation style references (Microsoft and Google) and more information about second person and imperative usage.
=> Update README.md for documentation repo

requirements.txt, source/mainnet/conf.py, source/testnet/conf.py
Need to be able to collapse sections of text.
Added sphinx toolbox extension to get the collapse functionality where you can collapse sections of text. Updated conf.py for both mainnet and testnet for this. Updated requirements.txt for the new extension.
=> Added collapse section functionality

source/shared/smart-contracts/tutorials/piggy-bank/testing.rst
_Describe the purpose of the pull request, link to issue describing the problem, etc.
=> Updated from_micro_gtu to from_micro_ccd

source/testnet/net/concepts/concepts.rst, source/testnet/net/guides/company-identities.rst
We need to describe the process of how to obtain a company identity on testnet as more exchanges start to integrate.
Added topic for company identities to testnet and adjusted content.
Closes #428
=> Added topic for company identities on testnet

source/testnet/net/guides/company-identities.rst
To correct the steps for requesting a company identity in testnet.
Added tools downloads back to steps.
=> Fix company identities request in testnet

source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
The new Android v2 release of the MW needed release notes and a Testnet download link.
Notes and link added.
=> Added release notes for Android v2 release, and Testnet downlod link

requirements.txt, source/mainnet/conf.py, source/testnet/conf.py
To have the possibility to consolidate topics, it would be useful to have tabbed content.
Added tabbed content extension to conf.py and to requirements.txt.
=> Added tabbed content extension

source/shared/smart-contracts/tutorials/piggy-bank/testing.rst
=> Fixed reference to gtu

source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/variables.rst, source/testnet/net/installation/downloads.rst, source/testnet/net/resources/release-notes.rst
Update release notes and downloads for Node 3.0.2.
Updated release notes pages for mainnet and testnet. Updated downloads pages for mainnet and testnet. Updated variables for mainnet.
=> Release notes for 3.0.2 node

source/mainnet/net/resources/release-notes-mainnet.rst, source/testnet/net/resources/release-notes.rst
To inform users about CCDScan.
Updated testnet and mainnet release notes
=> CCDScan release notes

source/shared/smart-contracts/general/develop-contracts.rst
Missing close parentheses at end of example.
Added the missing close parentheses.
Closes #437
=> Add missing bracket to smart contracts topic

source/shared/net/guides/overview-baker-process.rst
Make the reason for creating a separate account as a baker more obvious.
Added text to step 4 to explain why you might want to create a separate account.
=> Refined text for DW section of Overview of Baker Process

source/mainnet/_templates/index.html
List of links at bottom of landing page had bullets.
Edited style to remove bullets
=> Remove bullets from unordered list at bottom of landing page

source/mainnet/net/installation/downloads-testnet.rst
Link to the newest mac node.
Change link
=> Link to the newest mac node

source/mainnet/net/installation/downloads-testnet.rst
Link to the signed concordium client for macOS on testnet.
Closes https://github.com/Concordium/concordium-client/issues/153.
- Change link
=> Link to the signed concordium client for macOS on testnet

source/mainnet/net/index.rst, source/mainnet/net/resources/sirius-testnet-reset.rst
Create landing page needed by marketing to refer to for testnet reset.
Added page for testnet reset.
=> Testnet reset landing page

source/mainnet/_templates/index.html
To make access quicker, we need links to release notes and CCDScan on the landing page.
Added links on landing page and styled the unordered list for the text container.
=> Add links to CCDScan and release notes to landing page

source/mainnet/net/installation/downloads-testnet.rst
Bug reported that the Windows package for client on testnet is not signed.
Added signed to the URL
Closes #516
=> Added signed to URL for concordium client windows package

source/mainnet/_templates/index.html
To make delegation visible on landing page and to fix issue with margins for text at bottom of page on phones and tablets.
Added card for delegation to landing page and adjusted margins for the containers at the bottom to improve appearance on phones and tablets.
=> Improve landing page design

source/mainnet/_templates/index.html
Adjust the landing page to use a grid format.
Adjusted index.html to use different styles to make modification and maintenance simpler.
=> Landing page grid

source/mainnet/net/guides/shielded-transfer.rst
Users were not aware that exchanges don't support shielded transfers.
Added warning to shielded transfer topic.
=> Warning about shielded transfers

source/mainnet/net/concepts/concepts-baker.rst, source/mainnet/net/concepts/concepts-delegation.rst, source/mainnet/net/desktop-wallet/delegation-dw.rst, source/mainnet/net/desktop-wallet/index.rst, source/mainnet/net/index.rst, source/mainnet/net/mobile-wallet/index.rst
The sidebar menu under wallets was starting to get ugly.
Added landing topics for DW and MW and grouped topics specific to those below.
Closes #521
=> Make sidebar menu more manageable

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Update documentation to release `v1.4.2` of the desktop wallet for macOS _only_.
- Updated release notes and download links for macOS.
=> Update documentation for desktop wallet 1.4.2

source/mainnet/smart-contracts/references/crypto-primitives.rst
=> Edits to crypto primitives reference

source/mainnet/net/guides/add-baker-desktop.rst, source/mainnet/net/guides/delegation.rst, source/mainnet/net/mobile-wallet/add-baker-mw.rst, source/mainnet/net/mobile-wallet/baker-mw.rst, source/mainnet/net/mobile-wallet/update-baker-mw.rst, source/mainnet/net/snippets/delegation-faq.rst
Link to the Delegation FAQ was missing in the delegation topic.
Added the link.
=> Added link to delegation FAQ in delegation topic

source/mainnet/net/guides/become-baker.rst, source/mainnet/net/guides/run-node.rst, source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/nodes/baker-docker.rst, source/mainnet/net/nodes/troubleshoot-docker.rst, source/mainnet/net/resources/sirius-testnet-reset-nodes.rst, source/mainnet/smart-contracts-v0/references/local-settings.rst, source/mainnet/smart-contracts/references/local-settings.rst, source/mainnet/variables.rst
Closes https://github.com/Concordium/concordium-node/issues/428
Replace references to the old concordium-software distribution.
=> Update documentation of the docker distribution.

source/mainnet/net/guides/developer-page.rst, source/mainnet/net/resources/glossary.rst
Fixing dead links for smart contracts and whitepaper.
Fixed the links.
=> Fixing dead links

source/mainnet/net/guides/become-baker.rst, source/mainnet/net/guides/run-node.rst, source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/nodes/baker-docker.rst, source/mainnet/net/nodes/troubleshoot-docker.rst, source/mainnet/net/resources/sirius-testnet-reset-nodes.rst, source/mainnet/smart-contracts-v0/references/local-settings.rst, source/mainnet/smart-contracts/references/local-settings.rst, source/mainnet/variables.rst
Reverts Concordium/concordium.github.io#546 as per Caro.
=> Revert "Update documentation of the docker distribution."

source/mainnet/net/guides/overview-desktop.rst
Inform users of the virtual hive domain address.
Added address to the step in Desktop Wallet.
Closes #547
=> Add virtual hive address

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst, source/mainnet/variables.rst
Inform users about 4.2.3 node release.
Update downloads pages and variables, add release notes.
=> 423 node release updates

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Update date to correct date in release notes.
Update date to correct date in release notes.
=> Update date in release notes

source/mainnet/net/guides/become-baker.rst, source/mainnet/net/guides/run-node.rst, source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/nodes/baker-docker.rst, source/mainnet/net/nodes/troubleshoot-docker.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst, source/mainnet/net/resources/sirius-testnet-reset-nodes.rst, source/mainnet/smart-contracts-v0/references/local-settings.rst, source/mainnet/smart-contracts/references/local-settings.rst, source/mainnet/variables.rst
Inform users about updates to client and cargo.
Release notes and download links updated.
=> Client and cargo version update

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Fix cargo-concordium version in the release notes.
=> Fix version of cargo-concordium in the release notes.

source/mainnet/net/guides/run-node.rst
Add what I did to make the docker setup work, on my setup.
=> Added a point to the troubleshooting of docker node

source/mainnet/net/guides/deciding-wallet.rst
Remove incorrect information in topic about deciding which wallet to use.
Changed sentence in table that said you have to use Concordium client to be a baker on mobile wallet.
=> Replace old sentence about mobile wallet

source/mainnet/net/desktop-wallet/install-ledger-app.rst
To add information about installing custom certificate when using Nano S Plus.
Added information about how to get the Ledger to recovery mode for the Nano S Plus.
Closes #568
=> Updated steps in Install Ledger app for Nano S Plus

source/mainnet/net/guides/run-node.rst
Fix an incorrect command instance.
=> Fix typo in one of the docker-compose command instances.

source/mainnet/net/guides/sdks-apis.rst
Let developers know we have Rosetta SDK. Remove Go SDK due to poor quality.
Updated SDKs and APIs topic.
=> Added Rosetta SDK and remove Go SDK

source/mainnet/net/guides/run-node.rst
Step 4 for the mainnet process was not the same as for testnet and was confusing.
Made step 4 the same.
=> Updated Docker node process

source/mainnet/net/concepts/concepts-backup.rst, source/mainnet/net/guides/company-identities.rst, source/mainnet/net/resources/release-notes.rst, source/mainnet/smart-contracts-v0/general/contract-schema.rst, source/mainnet/smart-contracts-v0/tutorials/piggy-bank/testing.rst, source/mainnet/smart-contracts/general/contract-schema.rst
User noticed some broken external links.
Fixing broken external links.
=> Fix broken external links

source/mainnet/net/resources/terms-and-conditions-mw-gen2.rst, source/mainnet/net/resources/terms-and-conditions-mw.rst
Adjust T&C dates
Changed dates
=> Change effective dates in T&C for both MWs

source/mainnet/net/resources/terms-and-conditions-mw-gen2.rst
Rename the wallet in T&C for new mobile wallet.
Remove variable in T&C and replace with name to cover both platforms.
=> Update name in new MW T&C

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Fix duplicate text due to multiple product name changes in release notes.
Release notes changed.
=> Fix release notes

source/mainnet/net/guides/run-node-windows.rst
Prerequisites was misspelled.
Change spelling
=> Fix spelling error in Windows node topic

source/mainnet/smart-contracts/references/host-fns.rst
Add/correct information about the invoke host function for v1 smart contracts
Added missing information.
Closes #612
=> Update to the invoke host function

source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/variables.rst
Inform users about the mainnet node release
Release notes, downloads page, checksum variable updated.
=> Mainnet node release Oct 2022

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/references/concordium-client.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst, source/mainnet/variables.rst
Inform users about update of Concordium Client.
Release notes, downloads page, note added to import section of cc topic.
=> Concordium client release October 2022

source/mainnet/net/resources/bw-licenses.rst, source/mainnet/net/resources/legal.rst, source/mainnet/net/resources/terms-and-conditions-bw.rst
Publish browser wallet legal info for submission approval.
Move the t&c and license notice to a separate pull request.
=> Browser wallet terms and conditions

source/mainnet/smart-contracts-v0/guides/initialize-contract.rst, source/mainnet/smart-contracts/guides/initialize-contract.rst, source/mainnet/smart-contracts/guides/interact-instance.rst
Martin noted some issues with the smart contract documentation during testing.
Correct flag for parameter-binary, add sender flag, add note about passing parameters with a file.
Closes #631, #632, #634
=> Improvements to smart contracts documentation

source/mainnet/net/guides/company-identities.rst
Remove repeated steps and fix link.
Remove repeated steps and fix link.
=> Corrections to company identity

source/mainnet/net/snippets/delegation-faq.rst
Make the last paragraph clearer.
Changed "will" to "may".
=> Minor correction to wording in FAQ

source/mainnet/net/guides/developer-page.rst, source/mainnet/net/guides/run-node-macos.rst, source/mainnet/net/guides/run-node-windows.rst, source/mainnet/net/guides/run-node.rst, source/mainnet/net/guides/sdks-apis.rst, source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/nodes/node-runner-service-configuration.rst, source/mainnet/net/references/grpc2.rst, source/mainnet/net/resources/release-notes.rst, source/mainnet/smart-contracts-v0/tutorials/piggy-bank/writing.rst
Inform users about the node release on Testnet
Closes https://github.com/Concordium/concordium-node/issues/552
Updated downloads and release notes.
=> Testnet node release October 2022

source/mainnet/smart-contracts/tutorials/wCCD/wCCD-front-end-set-up.rst, source/mainnet/smart-contracts/tutorials/wCCD/wCCD-full-dApp.rst
Update the tutorial to reflect that the browser wallet is now released.
Replaced product with variable. Made adjustments to workflow one to do direct install.
=> Update wCCD tutorial to reflect a released BW

source/mainnet/net/browser-wallet/setup-browser-wallet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/mobile-wallet-gen2/setup-mobile-wallet.rst
To correct a couple of things and be more specific about the downloads.
In the Android wallet setup topic removed reference to iPhone. Made the download link point to the heading in downloads. In BW setup topic made the download link point to the heading in downloads.
=> Minor corrections to Android wallet and BW topics

source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/variables.rst
Inform users about changes for mainnet node release
Updated downloads, variables. Added release note.
=> Updates for mainnet node release

source/mainnet/net/guides/run-node-ubuntu.rst, source/mainnet/net/nodes/run-node-ubuntu.rst, source/mainnet/smart-contracts/tutorials/piggy-bank/preparing.rst
The new node supports Ubuntu 22.04 in addition to 20.04. This pull requests adds the new Ubuntu version to the listed requirements.
Added 22.04 to the Ubuntu requirements.
=> Add Ubuntu 22.04 support.

source/mainnet/smart-contracts/general/develop-contracts.rst, source/mainnet/smart-contracts/references/host-fns.rst
Add more information to the smart contract queries
=> Extend documentation for smart contract queries

source/mainnet/net/guides/deciding-wallet.rst
Make it clear to users which wallet is supported on various platforms
Added row to table in deciding wallet.
=> Add row regarding platform for wallets

source/mainnet/_templates/index.html, source/mainnet/_templates/layout.html
Remove analytics so as not to annoy users while trying to implement the new.
Removed include analytics.
=> Remove analytics temporarily from doc site

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst, source/mainnet/variables.rst
Inform users about updates of cargo and client tools for P5.
Downloads and release notes created.
=> Testnet tools update Nov 2022

source/mainnet/smart-contracts/guides/build-schema.rst
closes #662
Add documentation for event schema.  This should be published once `cargo-concordium` version 2.4.0 is live.
=> Add documentation for event schema

source/mainnet/_templates/404.html
Analytics was still enabled on 404 page.
Removed analytics include at bottom of file.
=> Disable analytics on 404 page

source/mainnet/conf.py
Based on feedback from Efiko, we need to provide a feedback button in the documentation.
Add feedback button to navbar menu icons.
=> Add feedback button to navbar menu icons

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Add version number for BW to release notes so users know what to look for in various versions.
Added version number to mainnet and testnet release notes.
=> Add version number for bw to release notes

source/mainnet/net/browser-wallet/connect-app.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
The wCCD box was placed below both wallet types (because I thought it would be done in time). It has been moved to under only web wallet. Also added version to release notes.
=> Correction to connect dapps topic

source/mainnet/net/guides/baker-pool.rst, source/mainnet/net/guides/run-node-macos.rst, source/mainnet/net/guides/run-node-ubuntu.rst, source/mainnet/net/guides/run-node-windows.rst, source/mainnet/net/guides/run-node.rst, source/mainnet/net/nodes/node-requirements.rst, source/mainnet/net/nodes/run-node-ubuntu.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Highlight to node runners and bakers that they can and should subscribe to status page updates.
Added note to a number of topics.
=> Add many notes about status page subscribe

source/mainnet/smart-contracts/guides/unit-test-contract.rst
Minor improvements to the quickcheck docs that were not included in the first PR.
- Describe the default test amount and direct attention to the comparison operator
=> Quickcheck docs: minor improvements

source/mainnet/smart-contracts/tutorials/nft-minting/index.rst
Forgot to change an instance of SDK reference to concordium client.
Changed the reference.
=> Correction to landing page for NFT tutorial

source/mainnet/net/browser-wallet/browser-wallet-faq.rst, source/mainnet/net/browser-wallet/setup-browser-wallet.rst, source/mainnet/net/guides/recover-wallet.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Inform users about release and clarify what to do in case of a forgotten passcode.
Release notes created. Added note in various topics.
Closes #706
=> Release for 0.9.5 BW and notes about forgotten passcode

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Release note for updated mac node.
Added release notes for testnet, mainnet. Updated downloads pages.
=> Testnet incident release

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Inform users about the 0.9.6 web wallet release
Release note for testnet, mainnet
=> BW 096 release notes

source/mainnet/net/guides/create-proofs.rst, source/mainnet/net/guides/developer-page.rst, source/mainnet/net/index.rst
Create proofs was duplicated in the TOC sidebar
Remove duplication
=> Fix duplication in TOC sidebar

source/mainnet/smart-contracts/guides/unit-test-contract.rst
Add a reentrancy example to the unit testing section
Closes  #435.
=> The DAO reentrancy example

source/mainnet/smart-contracts/guides/unit-test-contract.rst
Clarify about the state updates in Reentrancy section.
=> Clarify about state updates

source/mainnet/net/guides/run-node.rst
Fix incorrect variable name in example configs.
=> Fix environment variable name.

source/mainnet/smart-contracts/best-practices/development.rst
Small fixes after comments by @DOBEN.
=> Fixes to best practices

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Inform users about changes to the gen2 android wallet.
Release notes
=> Release info for Android MW 1.1.4 on testnet

source/mainnet/net/resources/release-notes-mainnet.rst
Inform users about android 1.1.4 release for mainnet
Release note
=> Android mw 114 release mainnet

source/mainnet/net/guides/developer-page.rst, source/mainnet/smart-contracts/tutorials/setup-env.rst
Inform users about availability of a testnet service node.
Added information in a couple of discreet locations.
=> Testnet service node

.github/workflows/deploy.yml
Fix the "Deploy" workflow.
Bump the action used to push the build to the newest version.
=> CI: Bump 'JamesIves/github-pages-deploy-action' to v4.4.1

source/mainnet/net/index.rst, source/mainnet/smart-contracts/general/introduction.rst, source/mainnet/smart-contracts/guides/contract-dev-guides.rst, source/mainnet/smart-contracts/guides/on-chain-index.rst, source/mainnet/smart-contracts/guides/quick-start.rst, source/mainnet/smart-contracts/references/index.rst, source/mainnet/smart-contracts/tutorials/index.rst
Make the smart contracts best practices topic more visible.
Add more cross references in various topics to the smart contracts best practices topic. Restructure TOC to place the topic more prominently.
=> Add more xrefs to sc best practices

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Inform users about the release of v3.2.0 of the Android legacy wallet.
Release notes
=> Android legacy release v3.2.0 release notes

source/mainnet/smart-contracts/guides/compile-module.rst, source/mainnet/smart-contracts/guides/no-std.rst, source/mainnet/smart-contracts/guides/setup-contract.rst
closes #752 
Explaining wee_alloc feature
=> Add wee_alloc feature documentation

source/mainnet/net/guides/run-node-windows.rst, source/mainnet/smart-contracts/tutorials/piggy-bank/deploying.rst
Minor corrections found when going through the tutorials.
One "\\" escape error and increase of gas limit *(needed 1244 NRG)*
=> Minor corrections

source/mainnet/smart-contracts/tutorials/fungible-tokens/index.rst, source/mainnet/smart-contracts/tutorials/fungible-tokens/smart-contract.rst
Minor changes to wording to make it fit better with purpose and to make the tutorial more generic.
Title and one sentence adjusted in index. Code text changed to make it more generic in smart contract topic.
=> Minor changes to fungible tokens tutorial

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Inform users about changes in 0.9.9 release.
Release notes
=> Browser wallet 0.9.9 release

source/mainnet/net/guides/low-code-nft-marketplace/marketplace.rst, source/mainnet/net/guides/low-code-nft-marketplace/minting-tool.rst, source/mainnet/smart-contracts/tutorials/fungible-tokens/index.rst, source/mainnet/smart-contracts/tutorials/nft-marketplace/index.rst
Corrections to two tutorials.
Updates to repo links, fix typo, adjust a heading and sentence.
Closes #789
=> Minor corrections to tutorials

source/mainnet/net/snippets/delegation-faq.rst
Add question about funds in release schedule to delegation FAQ.
Add question about funds in release schedule to delegation FAQ.
=> Add question to delegation FAQ

requirements.txt
Update babel version to solve failing linter
Bump babel version to latest released in requirements.txt
=> Bump babel version

source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
=> Fix release note link

source/mainnet/smart-contracts/tutorials/wCCD/wCCD-front-end-set-up.rst
A user reported a missing step in the wCCD tutorial. https://github.com/Concordium/concordium-browser-wallet/issues/311
Added step to the wCCD front end tutorial topic.
=> Add step to wCCD front-end tutorial

source/mainnet/net/concepts/id-accounts.rst, source/mainnet/net/guides/create-identity.rst
Add note in documentation about eID support.
Added note to create identity and identity concepts topics that states that users in Denmark who use DTS to obtain an ID can use mitID.
=> Note for eID support

source/mainnet/net/concepts/id-accounts.rst, source/mainnet/net/guides/create-account.rst, source/mainnet/net/guides/create-identity.rst, source/mainnet/net/guides/deciding-wallet.rst, source/mainnet/net/references/manage-accounts.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/net/resources/release-notes.rst
Inform users about release of legacy 3.2.0 iOS wallet.
Release notes, update a number of files to change note that identity and account creation is not supported any longer. Remove instructions about how to create identities and accounts.
=> iOS Legacy 3.2.0 release

source/mainnet/net/browser-wallet/browser-wallet-faq.rst, source/mainnet/net/browser-wallet/setup-browser-wallet.rst, source/mainnet/net/guides/deciding-wallet.rst
Add note about supported devices for BW.
Added info to 3 topics.
=> Add note about supported devices for BW

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/resources/release-notes.rst, source/mainnet/variables.rst
Inform users about change in 5.4.2 node release on testnet.
Release notes, variable, downloads
=> 5.4.2 testnet node release

source/mainnet/smart-contracts/guides/compile-module.rst, source/mainnet/smart-contracts/guides/setup-tools.rst, source/mainnet/smart-contracts/tutorials/setup-env.rst
Inform users about need to use version 1.69 of the compiler due to known issue.
Add note to setup tools and setup env topics. Add line to compile topic about the error with link to the setup tools.
=> Smart contract rustup compiler issue

source/mainnet/net/guides/graviton-hackathon.rst
Update graviton hackathon workshop dates
=> Update graviton hackathon workshop dates

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/resources/release-notes-mainnet.rst, source/mainnet/variables.rst
Inform users about the mainnet node release
Release notes; update downloads, previous downloads, variables.
=> Mainnet node release 5.4.2

source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst
Remove the versions for cargo and vs code extension on downloads pages since they will not be distributed in the old way.
Downloads pages updated.
=> Remove versions for cargo and vscode extension

source/mainnet/net/guides/dapp-examples.rst, source/mainnet/net/guides/developer-page.rst, source/mainnet/net/installation/downloads-testnet.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/smart-contracts/guides/deploy-module.rst, source/mainnet/smart-contracts/guides/initialize-contract.rst, source/mainnet/smart-contracts/guides/quick-start.rst, source/mainnet/smart-contracts/guides/setup-tools.rst
Inform users about front end deploy and initialize tool.
=> Smart contract front end tool documentation

source/mainnet/net/guides/dapp-examples.rst
Add wallet test bench to dApp examples
Add wallet test bench to dApp examples
=> Add wallet test bench to dApp examples

source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about content of 1.1.1 release.
Release note
=> iOS 1.1.1 release

source/mainnet/net/guides/company-identities.rst
The old configuration files were incorrect so I have uploaded the correct ones now. Sorry about that.
This PR updates checksums of the downloads.
=> The tools have been updated so updating checksums.

source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about the release of CCDScan.
Release notes
=> CCDScan release August 2023

source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about the 1.1.8 release contents.
Release notes
=> BW 1.1.8 release

source/mainnet/net/guides/create-proofs.rst, source/mainnet/net/guides/developer-page.rst, source/mainnet/net/web3-id/index.rst
Inform users about the existence of the proof explorer.
Add proof explorer and correct one broken link
=> Add proof explorer to relevant pages

source/mainnet/net/guides/create-proofs.rst, source/mainnet/net/guides/developer-page.rst
=> Additional sentence about proof explorer

source/mainnet/smart-contracts/tutorials/smartContractUpgrade/smartContractUpgrade.rst
=> Updated gRPC port

source/mainnet/net/nodes/node-requirements.rst
The link did not display as a link.
=> Fix prometheus link.

source/mainnet/net/installation/downloads.rst
Fix node download links for mainnet versions of Windows and Mac. (Fixes issue Pablo pointed out in Slack.)
Update downloads file.
=> Fix mainnet node versions - Windows and Mac

source/_templates/404.html
Fix issue with the 404 page, where it fails to load backgound image and logo.
=> Fix image links in 404 page

source/mainnet/net/guides/sdks-apis.rst
Solves part 1 of #907
The second part of the issue requires a more work and a PR in another repo first. So will be postponed.
=> Add `ccd-js-gen` in the list of useful NPM packages

source/mainnet/smart-contracts-v0/guides/setup-tools.rst
Update the instructions for how to install cargo in the V0 smart contracts documentation
Update cargo section of Setup tools topic.
closes #905
=> Update cargo instructions for V0 SC

source/mainnet/net/installation/downloads.rst
Fix the dropdown in the dropdown for Linux DW downloads on Mainnet
Remove extra dropdown and adjust indent.
=> Fix linux DW downloads

source/mainnet/smart-contracts/general/contract-schema.rst
=> Update schema embedded key

source/mainnet/smart-contracts/general/contract-schema.rst
Update custom section logic for schemas.
Follow up on PR https://github.com/Concordium/concordium.github.io/pull/922
=> Update custom section logic for schemas

source/mainnet/smart-contracts/tutorials/sponsoredTransactions/sponsoredTransactionsSmartContract.rst
Correct a sentence in the sponsored transactions tutorial.
Hamid suggested a change to the wording of a sentence about the signature and keys.
=> Correction to sponsored transactions tutorials

source/mainnet/net/mobile-wallet/update-baker-mw.rst, source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about the changes in the BW release.
Release notes
Change update pool settings screenshot and text for BW for commissions.
=> BW release Nov 2023

source/mainnet/net/guides/run-local-chain.rst
Update the local chain docs for P6. Closes https://github.com/Concordium/concordium.github.io/issues/924.
@dg-concordium I didn't remove the mention of a finalization committee, as we may have stopped using the term, but the concept still remains in our software.
@abizjak As I understand it, the one-click chain tool is not yet finished. So I haven't added a link to it yet.
- Update docs.
=> Update the local chain docs for P6

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Inform users about the content of the mainnet 6.2.3 node release
Release notes
Downloads
Previous downloads
Variables
=> Mainnet 6.2.3 node release

source/mainnet/net/snippets/delegation-faq.rst
Add question to FAQ to direct legacy wallet users how to adjust commission rates for their pools.
Delegation FAQ topic
=> Delegation FAQ addition for legacy wallet pools

source/mainnet/net/guides/how-to-earn.rst, source/mainnet/net/guides/learn-about-concordium.rst, source/mainnet/net/guides/wallet-faqs.rst, source/mainnet/net/index.rst, source/mainnet/net/resources/glossary.rst
Update links in the documentation and make it less confusing.
Remove legal from TOC
Update whitepaper link
Add text to indicate sub-topics 
=> Update links in doc

source/mainnet/conf.py
After UI changes, the navigation depth of the sidebar needed to be adjusted.
Add navigation depth: 5 to conf.py.
=> Change navigation depth to show more in sidebar

source/mainnet/net/guides/developer-page.rst, source/mainnet/net/installation/downloads.rst, source/mainnet/smart-contracts-v0/guides/setup-tools.rst, source/mainnet/smart-contracts/general/introduction.rst, source/mainnet/smart-contracts/guides/initialize-contract.rst, source/mainnet/smart-contracts/guides/interact-instance.rst, source/mainnet/smart-contracts/guides/setup-tools.rst, source/mainnet/smart-contracts/guides/upgradeable-contract.rst, source/shared/setup-env.rst
Add the recently published smart contract tutorial videos to the documentation.
Added links to videos where needed in documentation.
Closes #945
=> Add links to SC videos

source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about the BW 1.3.0 release.
Release note
=> BW 130 release

source/_templates/analytics.html
Add hubspot code from marketing to analytics
analytics html file config
=> Add hubspot code to analytics

source/mainnet/net/guides/dapp-examples.rst, source/mainnet/smart-contracts/guides/quick-start.rst
This PR adds 'tip' blocks for mentioning the concordium dapp starter template.
=> Add tips about using the dapp starter template

source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about the contents of the release.
Release note
=> BW 1.4.0 release Feb 2024

source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about changes in the release.
Release note
=> Browser wallet 1.4.1 release

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Inform users about changes in the release.
Release notes
Variables
Previous node releases
Downloads
=> Testnet 6.3.x node release

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Inform users about changes in 6.3.0 release
Release notes
Downloads
Previous node downloads
Variables
=> 6.3.0 node release for mainnet

source/mainnet/net/guides/dapp-examples.rst, source/mainnet/net/guides/developer-page.rst, source/mainnet/net/web3-id/issuer.rst
Update dapp examples and add missing ew examples.
Update dapp examples and add missing new examples.
=> Update dapp examples

source/mainnet/smart-contracts/tutorials/counter/counter-contract.rst, source/shared/setup-env.rst
Update SC tutorial information
Tutorial setup, counter tutorial
=> SC tutorials doc updates

source/mainnet/net/release-notes/release-notes-lp.rst
Inform users about content of the release.
Release notes
=> BW 1.4.2 release

source/mainnet/net/release-notes/release-notes-lp.rst
=> BW 1.4.3 release

source/mainnet/smart-contracts/guides/no-std.rst
Add `bump_alloc` feature documentation.
Add `bump_alloc` feature documentation.
=> Add bump alloc feature documentation

source/mainnet/net/guides/dapp-examples.rst
Add track and trace dapp link
Add track and trace dapp link
=> Add track and trace dapp link

source/mainnet/net/release-notes/release-notes-lp.rst
Add CryptoX Android 1.0.0 release notes
- Added CryptoX Android 1.0.0 release notes
=> Add CryptoX Android 1.0.0 release notes

source/mainnet/net/guides/wallet-sdk/wallet-sdk-account-transaction.rst, source/mainnet/net/guides/wallet-sdk/wallet-sdk-credential-deployment.rst, source/mainnet/net/guides/wallet-sdk/wallet-sdk-identity-creation.rst, source/mainnet/net/guides/wallet-sdk/wallet-sdk-identity-recovery.rst, source/mainnet/net/guides/wallet-sdk/wallet-sdk.rst
Try and actually follow the structure of the existing docs
=> Revise Swift SDK docs

source/mainnet/net/resources/terms-and-conditions-cryptox.rst
Can be viewed at `/net/resources/terms-and-conditions-cryptox.html`
- Adds separate page with terms and conditions for cryptox
=> Add cryptox terms and conditions

source/mainnet/net/installation/downloads.rst, source/mainnet/net/references/concordium-client.rst
**This should be merged with the next release of `concordium-client`**
Update the download/use instructions for `concordium-client` in line with the changes to how it is distributed for Windows.
- Include unzipping directions with respect to the Windows concordium-client distribution.
- Separate out running directions for Mac, Linux and Windows, and update the Windows directions.
=> Update concordium-client directions

source/mainnet/net/release-notes/release-notes-lp.rst
Add release notes for 1.1.0 and 1.1.1
- Add release notes for 1.1.0 and 1.1.1
=> CryptoX 1.1.0 and 1.1.1 releases

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Update documentation for 6.3.1 testnet release.
- Release notes
- Variables
- Previous node releases
- Downloads
=> Testnet node release version 6.3.1.

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Update documentation for version 6.3.1 mainnet node release.
-    Release notes
-    Variables
-    Previous node releases
-    Downloads
=> Mainnet node release version 6.3.1

source/mainnet/conf.py, source/mainnet/net/installation/downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Desktop wallet release 1.7.4
Desktop wallet release 1.7.4
=> Desktop wallet release 1.7.4

source/mainnet/net/installation/downloads.rst
Add CryptoX download links.
- Add CryptoX download links to the downloads page
=> Add CryptoX download links

source/mainnet/net/release-notes/release-notes-lp.rst
Add sunsetting release notes for Concordium Mobile wallets.
- Add Legacy Android wallet 3.4.0 release
- Add Android Phrase wallet 1.7.0 release
=> Concordium Mobile sunsetting

source/mainnet/net/release-notes/release-notes-lp.rst
Add browser wallet 1.6.1 release notes
=> Add browser wallet 1.6.1 release notes

source/mainnet/net/release-notes/release-notes-lp.rst
Add browser wallet release notes for 1.6.3
=> Add BW release 1.6.3

source/mainnet/net/release-notes/release-notes-lp.rst
Add release notes for browser wallet release 1.6.4
=> Add release notes for browser wallet 1.6.4

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Update release notes and download links for new node and concordium-client releases.
- Testnet release of node 7.0.4
- Release of concordium-client 7.0.1
=> Release node 7.0.4 for testnet and concordium-client 7.0.1.

source/mainnet/net/installation/downloads.rst, source/mainnet/net/installation/previous-node-downloads.rst, source/mainnet/net/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Release new node versions.
- Release notes and links for 6.3.2 mainnet release
- Release notes and links for 7.0.5 testnet release
=> Release node 6.3.2 for mainnet and 7.0.5 for testnet.

.github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, .github/workflows/linkcheck-mainnet.yml, .github/workflows/lint.yml, .github/workflows/remove-preview.yml
Fix CI by using a fixed python version
=> Setup python version exlicitly in CI

source/mainnet/net/release-notes/release-notes-lp.rst
=> BW 1.7.1 release

source/mainnet/net/release-notes/release-notes-lp.rst
Update to release notes
Added release note for CryptoX for iOS 2.0.0
=> Release note for CryptoX for iOS 2.0.0

source/mainnet/net/release-notes/release-notes-lp.rst
Release notes update
Added line about ZK support for company identities
=> BW 1.7.1 release DOC update

source/mainnet/tutorials/nft-minting/build-smart-contract.rst, source/mainnet/tutorials/nft-minting/index.rst, source/mainnet/tutorials/nft-minting/upload-nft.rst
Improve NFT tutorial, add more references, more suggestive example
- Removed old version for cargo-generate
- Added IPFS references and a reference to the Tools section
- Enhanced the attributes example to be more suggestive 
=> Improve NFT tutorial, add more references, more suggestive example

source/mainnet/net/guides/cryptox-faq.rst, source/mainnet/net/guides/remove-delegation.rst, source/mainnet/net/guides/update-delegation.rst, source/mainnet/net/mobile-wallet/update-baker-mw.rst, source/mainnet/net/snippets/delegation-faq.rst
Removed P7 disclaimer.
Note was deleted.
=> Removed P7 disclaimer

source/mainnet/tutorials/wCCD/wCCD-frontend-set-up.rst, source/mainnet/tutorials/wCCD/wCCD-interacting.rst, source/mainnet/tutorials/wCCD/wCCD-introduction.rst
Improve the wCCD tutorial.
- Removed unnecessary wallet tutorial and replaced with a reference, images were not deleted, only references to them, they will be deleted after new screenshots are made with the new wallet UI
- Formatted commands for better readability, by adding a space after "$" and removing "./", which is not necessary, as `concordium-client` should be added to the `PATH`
- Replaced wrong 8080 port with 4173, as that's the port the app will run on because of Vite
- Removed the link to [proxy-implementation-upgradable wccd](https://github.com/Concordium/concordium-rust-smart-contracts/pull/128) as that is a closed pull request, it was replaced by [natively-upgradable wccd](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis2-wccd/src/lib.rs) …
=> Updated wCCD tutorial

source/mainnet/net/release-notes/release-notes-lp.rst
Adding release note for Concordium Wallet for Android v. 1.8.0
Added the release note.
=> Added release note for Concordium Wallet 1.8.0 for Android

source/mainnet/tutorials/eSealing/eSealing_dapp.rst
Update eSealing tutorial
- updated wrong reference to setup wallet
- formatted commands
=> Updated wrong reference, formatted commands

source/mainnet/tutorials/sponsoredTransactions/index.rst, source/mainnet/tutorials/sponsoredTransactions/sponsoredTransactionsSmartContract.rst
Update and verify the sponsored transactions tutorial
- added a reference to `nonce` wiki explanation page
- added a reference to explain the `recurse-submodules` git flag
- added a reference to explain the `nocapture` cargo flag
- added an extra sentence explaining the role of `6372`, the smart contract index in a command
- formatted commands by adding a space after `$`
=> Added more references, explanations and formatted commands

source/mainnet/docs/network/guides/baker-docker.rst, source/mainnet/docs/network/guides/baker-macos.rst, source/mainnet/docs/network/guides/baker-ubuntu.rst, source/mainnet/docs/network/guides/baker-windows.rst, source/mainnet/docs/network/guides/become-baker.rst, source/mainnet/docs/network/guides/validation-with-wallets.rst
Review and modify the Run a validator articles
Note: The [Add a validator](https://developer.concordium.software/pr-preview/pr-1066/en/mainnet/docs/mobile-wallet/add-baker-mw.html#add-a-validator) article, which is essential for all the other articles modified in this PR, is in a different Wallet section and referenced in the Validation section. It is suitable both in the Wallet section, as it does include wallet tutorials and in the validation section, as it is necessary to follow in order to become a validator. Suggestions are appreciated on where it should remain.
Note: The [Validation with the Concordium Client](https://developer.concordium.software/pr-preview/pr-1066/en/mainnet/docs/network/guides/become-baker.html#validation-with-the-concordium-client) article was not reviewed …
=> Modified Run a validator articles 

source/mainnet/conf.py
Fix this broken link: 
https://developer.concordium.software/en/mainnet/net/guides/tools/developer-page.html
Add a redirect to new location of the page
=> Added redirect for broken link

source/mainnet/conf.py
_Describe the purpose of the pull request, link to issue describing the problem, etc.
=> Updated link in conf.py

source/mainnet/conf.py
Fix broken links.
Added missing redirects of five files in conf.py.
=> Added missing redirects of five pages

source/mainnet/conf.py
Fixing broken links
Updated redirect paths in conf.py
=> Fixed redirect paths

source/mainnet/conf.py
Fix redirects, this is a test with just 1 scenario.
Changed from a relative redirect to an absolute one
=> New redirect method

source/mainnet/conf.py
Hotfix a broken redirect:
https://developer.concordium.software/en/mainnet/docs/protocol/id.accounts.html
- redirect fixed
=> Hotfix a broken redirect

source/mainnet/docs/smart-contracts/contract-instances.rst, source/mainnet/docs/smart-contracts/contract-lifecycle.rst, source/mainnet/docs/smart-contracts/contract-module.rst, source/mainnet/docs/smart-contracts/develop-contracts.rst, source/mainnet/docs/smart-contracts/guides/build-contract.rst, source/mainnet/docs/smart-contracts/introduction.rst
Finished review on "What is a smart contract?" section.
Added references and replaced one broken link. 
Added references and replaced one broken link. 
=> Finished review on What is a smart contract section

source/mainnet/docs/smart-contracts/guides/setup-contract.rst, source/mainnet/docs/smart-contracts/introduction.rst, source/mainnet/tools/wallet-sdk/wallet-sdk-account-transaction.rst, source/mainnet/tools/wallet-sdk/wallet-sdk-credential-deployment.rst, source/mainnet/tools/wallet-sdk/wallet-sdk-identity-creation.rst, source/mainnet/tools/wallet-sdk/wallet-sdk-identity-provider.rst, source/mainnet/tools/wallet-sdk/wallet-sdk-identity-recovery.rst, source/mainnet/tools/wallet-sdk/wallet-sdk.rst
The [pyData official documentation](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/web-components.html#sphinx-design-components) which we use mentions that the recommended `tabs` extension is `Spinx Design`;
Up to now, we were using [sphinx-tabs](https://sphinx-tabs.readthedocs.io/en/latest/#sphinx-tabs) which was not compatible with dark mode;
This was changed, appropriate extension is used now;
- changed tabs extension
=> Changed tabs extension to a more compatible one

source/mainnet/conf.py
Replaced wrong redirect with correct page
Replaced wrong redirect with correct page
=> Replaced wrong redirect with correct page

source/mainnet/docs/smart-contracts/guides/deploy-module.rst, source/mainnet/docs/smart-contracts/guides/initialize-contract.rst, source/mainnet/docs/smart-contracts/guides/inspect-instance.rst, source/mainnet/docs/smart-contracts/guides/interact-instance.rst, source/mainnet/docs/smart-contracts/guides/invoke-instance.rst
Review and modify, if necessary, the `deploy` section of smart contracts.
- changed one incorrect reference
- added a reference to `JSON Parameters`
=> Finished review of deploy section

source/mainnet/conf.py
Add WIP banner
- used the `announcement` theme option from PyData
=> Add WIP banner

source/mainnet/docs/protocol/concepts-baker.rst
Cleared up max size of pool statement in validation concepts article
=> Cleared up max size of pool statement

source/mainnet/docs/release-notes/release-notes-lp.rst
Adding release notes
Updated release notes with CryptoX for iOS v. 3.0.0
- [x ] I have performed a self-review of the changes.
=> Updated release notes with CryptoX for iOS v. 3.0.0

public/robots.txt, source/mainnet/conf.py
update sitemap config for new URL
- changed config
=> update sitemap config for new URL

source/mainnet/docs/release-notes/release-notes-lp.rst
The purpose of the pull request is to update the release notes with info on CryptoX for Android v. 1.4.0.
Added  CryptoX for Android v. 1.4.0.
=> Updated release notes with info on CryptoX for Android version 1.4.0

source/mainnet/conf.py
The purpose of the pull request is to fix broken links on the web site by redirecting documentation pages.
Updated the conf.py file.
=> Redirect pages

source/mainnet/docs/release-notes/release-notes-lp.rst
Update release notes with BW1.7.2
=> Update release notes with BW1.7.2

source/mainnet/conf.py
Redirect old bw licences link
- redirect old bw licences link to [t&c page](https://docs.concordium.com/en/mainnet/docs/guides/cryptox-terms.html)
=> Redirect bw linceses link

source/mainnet/docs/network/guides/run-local-chain.rst, source/mainnet/docs/network/nodes/run-node.rst
Update run a node in docker articles
- remove obsolete `version` attribute
- add `platform: linux/amd64` for non linux devices
=> Update run a node in docker articles

source/mainnet/conf.py
Redirect legal link to terms page
- add new redirect
=> Redirect legal

source/mainnet/docs/index.rst
Add note regarding rust versioning to homepage
=> Add note regarding versioning to homepage

source/mainnet/tutorials/index.rst
Slightly modify tutorials home page
- move `piggy bank` to advanced applications
- remove `semi fungible token` from this page
- move `eSealing` to Advanced Applications and remove it's separate section
- rename `Advanced Features` to `Advanced Concordium Features`
- change redirect from `development best practices` to `best practices index`
=> Modify tutorials home page

source/mainnet/docs/index.rst
Move the note regarding versioning after the homepage image and links
- moved note
=> Move the note in the homepage

source/mainnet/docs/index.rst, source/mainnet/docs/voting/gc-voting.rst
Update of the page Concordium Governance Committee elections after technical review by Science team and language review by TKT.
Updated the page plus the index.rst that includes it.
=> Update governance committee elections page

source/mainnet/docs/release-notes/release-notes-lp.rst
Add release note for CryptoX 1.5.0 for Android
Updated Release notes page
=> Added release note for CryptoX 1.5.0 for Android

source/mainnet/docs/voting/coordinator.rst
To update the Election coordinator tool page after technical review by Science Team and language review by TKT.
- Updated page.
- Deleted commands in the last section (to avoid redundancy and to make documentation maintenance easier), wrote short text about key functionality and added link to:
https://www.google.com/url?q=https://github.com/Concordium/concordium-governance-committee-voting/tree/main/coordinator-tool&sa=D&source=docs&ust=1738057670196284&usg=AOvVaw3eyG5QxxNsC0sn9zYhstHK
=> Updated Election coordinator tool

source/mainnet/docs/release-notes/release-notes-lp.rst
=> BW 2.0.0 release

source/mainnet/docs/release-notes/release-notes-lp.rst
=> BW 2.0.1 and 2.0.2 release notes

source/mainnet/conf.py
Fix sctools redirect, there was a broken link in sctools.
=> Fix sctools redirect

source/mainnet/docs/index.rst, source/mainnet/docs/smart-contracts/guides/build-contract.rst, source/shared/setup-env.rst
Update note regarding `cargo concordium` version
- note updated
=> Update note regarding cargo concordium version

source/mainnet/docs/index.rst, source/mainnet/docs/smart-contracts/guides/build-contract.rst, source/shared/setup-env.rst
Fix instruction to update cargo concordium version
=> Fix instruction to update cargo concordium version

source/mainnet/docs/release-notes/release-notes-lp.rst
=> BW 2.1.2 release

source/mainnet/conf.py
Fix broken links from the onboarding guide for exchanges.
=> Fix broken links

source/mainnet/docs/guides/ledger-tutorial.rst
Remove firmware mention, all devices need firmware updated, not just Nano S
=> Remove firmware mention

source/mainnet/docs/desktop-wallet/create-credentials-file.rst, source/mainnet/docs/desktop-wallet/install-ledger-app.rst, source/mainnet/docs/desktop-wallet/multisig-simple-transfer.rst, source/mainnet/docs/desktop-wallet/sign-transaction.rst, source/mainnet/docs/guides/add-delegation.rst, source/mainnet/docs/guides/create-account.rst, source/mainnet/docs/guides/create-identity.rst, source/mainnet/docs/guides/deciding-wallet.rst, source/mainnet/docs/guides/multisig-transfer.rst, source/mainnet/docs/guides/overview-desktop.rst, source/mainnet/docs/guides/remove-delegation.rst, source/mainnet/docs/guides/send-ccd-wallets.rst, source/mainnet/docs/guides/shield-ccd-wallets.rst, source/mainnet/docs/guides/update-delegation.rst, source/mainnet/docs/mobile-wallet/add-baker-mw.rst, source/mainnet/docs/mobile-wallet/stop-validator.rst, source/mainnet/docs/mobile-wallet/update-baker-mw.rst
To remove mentioning of the Nano S ledger device from documentation.
Removed mentioning of the Nano S in various files throughout documentation. Either removed it completely or replaced it with "ledger device", depending on the context.
=> Deleted mentioning of Nano S in various files throughout documentation

source/mainnet/tools/developer-page.rst
Updated links in the "Social media and support" section
=> Updating dev res links

source/mainnet/docs/release-notes/release-notes-lp.rst
Add release notes for  CryptoX iOS v. 3.2.2
=> added release notes for CryptoX iOS v. 3.2.2

source/mainnet/community/aesirx-interview.rst, source/mainnet/community/developer-spotlight.rst, source/mainnet/community/devnet.rst, source/mainnet/community/index.rst
Expanding the Community section
Added a new page to the Community section - Developer Spotlight, and also added an interview with the founder of the AesirX project.
=> added new page - developer spotlight

source/mainnet/docs/release-notes/release-notes-lp.rst
=> BW 2.2.0 release

source/mainnet/docs/release-notes/release-notes-lp.rst
Update release-notes-lp.rst for CryptoX iOS
=> Update release-notes-lp.rst for CryptoX iOS

source/mainnet/docs/protocol/transaction-fees.rst, source/mainnet/docs/resources/glossary.rst
Update the spelling of gas to follow capitalization conventions for this term in blockchain terminology.
Updated the following files:
- Transaction fees
- Glossary
=> updated the spelling of gas to follow capitalization conventions

source/mainnet/docs/protocol/identity.rst
Fix typo  on page Identity framework on Concordium
identity,rst was updated.
- x ] I have performed a self-review of the changes.
- x ] I have documented my code, in particular the intent of the
=> fixed typo in identity doc

source/mainnet/docs/release-notes/release-notes-lp.rst
-   Removed Google Analytics track screens and events
=> BW 2.4.0 release

source/mainnet/docs/release-notes/release-notes-lp.rst
-   Added Fiat on-ramp in the Browser Wallet.
=> BW 2.5.0 release

source/mainnet/docs/protocol/manage-accounts.rst
Add more explanations to account aliases section, including links to code examples.
=> Add more explanations to alias section

source/mainnet/tutorials/index.rst, source/shared/setup-env.rst
Rename tutorials section as not all of the tutorials in there are about smart contracts.
=> Rename tutorials section

source/mainnet/docs/release-notes/release-notes-lp.rst
=> BW 2.5.1 release

source/mainnet/docs/network/guides/import-validator-keys.rst, source/mainnet/docs/network/nodes/run-node-ubuntu/run-node-ubuntu.rst
Update minimum supported `ubuntu` version for a node
=> Update min ubuntu version for a node

source/mainnet/docs/plt/examples/concordium-client.rst, source/mainnet/docs/plt/examples/web-sdk.rst, source/mainnet/docs/plt/operations/index.rst
Update version for PLT docs, for `web-sdk` and download links for `concordium-client`
=> Update version for PLT docs

source/mainnet/docs/plt/examples/rust-sdk.rst, source/mainnet/docs/plt/operations/index.rst
Update version of rust sdk for plt development
=> Update version of rust sdk for plt development

source/mainnet/docs/installation/downloads.rst
LInks for Desktop Wallet testnet 1.9.0 were updated
=> Updated download links for desktop wallet testnet 1.9.0

source/mainnet/docs/help-and-faq/faqs.rst, source/mainnet/docs/help-and-faq/set-up-doc-env.rst, source/mainnet/docs/help-and-faq/style-guide.rst
Update the guide for contributing to the docs, make it universal, not only for macOS
- [z] I accept the above linked CLA.
=> Update the guide for contributing to the docs

source/mainnet/docs/installation/downloads.rst, source/mainnet/docs/installation/previous-node-downloads.rst, source/mainnet/docs/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Update release notes and download links for 9.0.7 mainnet node release.
=> Release notes and download links for 9.0.7 (mainnet).

source/mainnet/docs/plt/examples/concordium-client.rst, source/mainnet/docs/plt/examples/index.rst, source/mainnet/docs/plt/examples/rust-sdk.rst, source/mainnet/docs/plt/operations/index.rst
Replace all mentions of devnet with testnet
=> Replace all mentions of devnet with testnet

source/mainnet/docs/release-notes/release-notes-lp.rst
=> BW 2.6.0 release

source/mainnet/docs/installation/downloads.rst, source/mainnet/docs/release-notes/release-notes-lp.rst, source/mainnet/variables.rst
Update docs with latest desktop wallet release.
=> Desktop wallet/version bump

source/mainnet/docs/plt/index.rst, source/mainnet/docs/plt/operations/index.rst, source/mainnet/docs/plt/setup-guide/index.rst
Update the PLT operations article for accuracy and usability.
PLT operations article:
- Deleted note mentioning MVP
- Moved links to examples further up for better visibility
- Added links to glossary for PLT terms
=> Update plt operations article

source/mainnet/docs/guides/ledger-tutorial.rst
To fix broken link in the article "Use your ledger device with Concordium Desktop Wallet" to https://www.concordium.com/wallet/end-users#wallet
Updated file: ledger-tutorial.rst
=> Fixed broken link

source/mainnet/docs/resources/glossary.rst
To update the glossary with approved terms from the internal glossary database.
- Added terms to glossary.rst
- Moved a term to the correct place in glossary
=> Add terms to glossary
